import { Country } from './Countries.ts'

export interface CityData {
  name: string
  x: number // Position in 10x10 grid (0-9)
  y: number // Position in 10x10 grid (0-9)
  population?: number // Optional, for reference
  isCapital?: boolean
}

// Major cities for each country (10-25 per country)
// Positioned on a 10x10 grid for each country view with MAXIMUM SPACING for clean line routing
export const CountryCities: Partial<Record<Country, CityData[]>> = {
  [Country.USA]: [
    { name: 'Washington DC', x: 5, y: 5, isCapital: true },
    { name: 'New York', x: 9, y: 2 },
    { name: 'Los Angeles', x: 0, y: 7 },
    { name: 'Chicago', x: 6, y: 3 },
    { name: 'Houston', x: 4, y: 9 },
    { name: 'Phoenix', x: 2, y: 7 },
    { name: 'Philadelphia', x: 8, y: 3 },
    { name: 'San Antonio', x: 3, y: 8 },
    { name: 'San Diego', x: 0, y: 9 },
    { name: 'Dallas', x: 4, y: 7 },
    { name: 'San Francisco', x: 0, y: 5 },
    { name: 'Seattle', x: 0, y: 1 },
    { name: 'Denver', x: 3, y: 5 },
    { name: 'Boston', x: 9, y: 0 },
    { name: 'Miami', x: 7, y: 9 },
    { name: 'Atlanta', x: 6, y: 7 },
    { name: 'Detroit', x: 7, y: 2 },
    { name: 'Las Vegas', x: 2, y: 6 },
    { name: 'Portland', x: 0, y: 3 },
    { name: 'New Orleans', x: 5, y: 8 },
  ],

  [Country.CHINA]: [
    { name: 'Beijing', x: 5, y: 4, isCapital: true },
    { name: 'Shanghai', x: 9, y: 6 },
    { name: 'Guangzhou', x: 6, y: 9 },
    { name: 'Shenzhen', x: 8, y: 9 },
    { name: 'Chengdu', x: 1, y: 6 },
    { name: 'Tianjin', x: 7, y: 3 },
    { name: 'Wuhan', x: 4, y: 7 },
    { name: 'Xian', x: 2, y: 5 },
    { name: 'Nanjing', x: 8, y: 5 },
    { name: 'Chongqing', x: 2, y: 8 },
    { name: 'Harbin', x: 8, y: 0 },
    { name: 'Urumqi', x: 0, y: 2 },
    { name: 'Lhasa', x: 0, y: 8 },
    { name: 'Kunming', x: 1, y: 9 },
    { name: 'Hangzhou', x: 9, y: 5 },
    { name: 'Shenyang', x: 9, y: 1 },
    { name: 'Dalian', x: 9, y: 3 },
    { name: 'Qingdao', x: 8, y: 4 },
    { name: 'Suzhou', x: 7, y: 6 },
    { name: 'Zhengzhou', x: 3, y: 4 },
  ],

  [Country.RUSSIA]: [
    { name: 'Moscow', x: 5, y: 5, isCapital: true },
    { name: 'St Petersburg', x: 2, y: 2 },
    { name: 'Novosibirsk', x: 8, y: 4 },
    { name: 'Yekaterinburg', x: 6, y: 3 },
    { name: 'Vladivostok', x: 9, y: 7 },
    { name: 'Nizhny Novgorod', x: 4, y: 4 },
    { name: 'Volgograd', x: 2, y: 8 },
    { name: 'Rostov-on-Don', x: 1, y: 7 },
    { name: 'Kazan', x: 6, y: 2 },
    { name: 'Omsk', x: 8, y: 3 },
    { name: 'Samara', x: 4, y: 7 },
    { name: 'Chelyabinsk', x: 7, y: 3 },
    { name: 'Kaliningrad', x: 0, y: 4 },
    { name: 'Krasnoyarsk', x: 9, y: 2 },
    { name: 'Irkutsk', x: 9, y: 5 },
    { name: 'Khabarovsk', x: 9, y: 6 },
    { name: 'Murmansk', x: 3, y: 0 },
    { name: 'Sochi', x: 0, y: 8 },
    { name: 'Perm', x: 6, y: 1 },
    { name: 'Ufa', x: 7, y: 2 },
  ],

  [Country.INDIA]: [
    { name: 'New Delhi', x: 4, y: 3, isCapital: true },
    { name: 'Mumbai', x: 1, y: 6 },
    { name: 'Bangalore', x: 4, y: 9 },
    { name: 'Kolkata', x: 9, y: 4 },
    { name: 'Chennai', x: 6, y: 9 },
    { name: 'Hyderabad', x: 5, y: 8 },
    { name: 'Ahmedabad', x: 1, y: 4 },
    { name: 'Pune', x: 2, y: 7 },
    { name: 'Surat', x: 0, y: 5 },
    { name: 'Jaipur', x: 2, y: 2 },
    { name: 'Lucknow', x: 7, y: 3 },
    { name: 'Kanpur', x: 7, y: 1 },
    { name: 'Nagpur', x: 5, y: 6 },
    { name: 'Patna', x: 8, y: 2 },
    { name: 'Bhopal', x: 3, y: 5 },
    { name: 'Kochi', x: 2, y: 9 },
    { name: 'Varanasi', x: 8, y: 3 },
    { name: 'Amritsar', x: 1, y: 1 },
    { name: 'Guwahati', x: 9, y: 2 },
    { name: 'Visakhapatnam', x: 7, y: 7 },
  ],

  [Country.GERMANY]: [
    { name: 'Berlin', x: 7, y: 4, isCapital: true },
    { name: 'Hamburg', x: 5, y: 0 },
    { name: 'Munich', x: 6, y: 9 },
    { name: 'Cologne', x: 1, y: 4 },
    { name: 'Frankfurt', x: 3, y: 6 },
    { name: 'Stuttgart', x: 2, y: 8 },
    { name: 'Dusseldorf', x: 0, y: 3 },
    { name: 'Dortmund', x: 1, y: 1 },
    { name: 'Leipzig', x: 7, y: 3 },
    { name: 'Dresden', x: 9, y: 3 },
    { name: 'Bremen', x: 4, y: 1 },
    { name: 'Hannover', x: 5, y: 2 },
    { name: 'Nuremberg', x: 5, y: 7 },
    { name: 'Essen', x: 0, y: 2 },
    { name: 'Bonn', x: 2, y: 5 },
  ],

  [Country.FRANCE]: [
    { name: 'Paris', x: 5, y: 3, isCapital: true },
    { name: 'Marseille', x: 6, y: 9 },
    { name: 'Lyon', x: 6, y: 6 },
    { name: 'Toulouse', x: 1, y: 8 },
    { name: 'Nice', x: 8, y: 9 },
    { name: 'Nantes', x: 0, y: 4 },
    { name: 'Strasbourg', x: 9, y: 2 },
    { name: 'Bordeaux', x: 0, y: 6 },
    { name: 'Lille', x: 5, y: 0 },
    { name: 'Rennes', x: 0, y: 2 },
    { name: 'Reims', x: 6, y: 2 },
    { name: 'Montpellier', x: 3, y: 9 },
    { name: 'Saint-Etienne', x: 4, y: 7 },
    { name: 'Le Havre', x: 3, y: 0 },
    { name: 'Grenoble', x: 7, y: 7 },
  ],

  [Country.UK]: [
    { name: 'London', x: 6, y: 8, isCapital: true },
    { name: 'Birmingham', x: 4, y: 6 },
    { name: 'Manchester', x: 2, y: 4 },
    { name: 'Glasgow', x: 2, y: 0 },
    { name: 'Liverpool', x: 1, y: 5 },
    { name: 'Edinburgh', x: 4, y: 0 },
    { name: 'Leeds', x: 6, y: 4 },
    { name: 'Sheffield', x: 5, y: 5 },
    { name: 'Bristol', x: 1, y: 7 },
    { name: 'Newcastle', x: 5, y: 2 },
    { name: 'Cardiff', x: 0, y: 7 },
    { name: 'Belfast', x: 0, y: 2 },
    { name: 'Nottingham', x: 6, y: 5 },
    { name: 'Southampton', x: 4, y: 9 },
    { name: 'Aberdeen', x: 6, y: 0 },
  ],

  [Country.JAPAN]: [
    { name: 'Tokyo', x: 7, y: 4, isCapital: true },
    { name: 'Osaka', x: 3, y: 6 },
    { name: 'Yokohama', x: 8, y: 4 },
    { name: 'Nagoya', x: 5, y: 5 },
    { name: 'Sapporo', x: 7, y: 0 },
    { name: 'Kobe', x: 2, y: 6 },
    { name: 'Kyoto', x: 4, y: 5 },
    { name: 'Fukuoka', x: 0, y: 7 },
    { name: 'Kawasaki', x: 7, y: 5 },
    { name: 'Saitama', x: 6, y: 3 },
    { name: 'Hiroshima', x: 1, y: 6 },
    { name: 'Sendai', x: 8, y: 2 },
    { name: 'Chiba', x: 8, y: 5 },
    { name: 'Kitakyushu', x: 0, y: 8 },
    { name: 'Niigata', x: 5, y: 2 },
    { name: 'Naha', x: 0, y: 9 },
    { name: 'Shizuoka', x: 6, y: 6 },
    { name: 'Kumamoto', x: 1, y: 8 },
    { name: 'Okayama', x: 2, y: 5 },
    { name: 'Nagasaki', x: 0, y: 9 },
  ],

  [Country.BRAZIL]: [
    { name: 'Brasilia', x: 5, y: 4, isCapital: true },
    { name: 'Sao Paulo', x: 7, y: 7 },
    { name: 'Rio de Janeiro', x: 8, y: 6 },
    { name: 'Salvador', x: 9, y: 3 },
    { name: 'Fortaleza', x: 8, y: 0 },
    { name: 'Belo Horizonte', x: 6, y: 6 },
    { name: 'Manaus', x: 1, y: 2 },
    { name: 'Curitiba', x: 5, y: 9 },
    { name: 'Recife', x: 9, y: 1 },
    { name: 'Porto Alegre', x: 3, y: 9 },
    { name: 'Belem', x: 4, y: 0 },
    { name: 'Goiania', x: 3, y: 5 },
    { name: 'Guarulhos', x: 6, y: 8 },
    { name: 'Campinas', x: 5, y: 7 },
    { name: 'Natal', x: 9, y: 2 },
  ],

  [Country.CANADA]: [
    { name: 'Ottawa', x: 7, y: 6, isCapital: true },
    { name: 'Toronto', x: 8, y: 7 },
    { name: 'Montreal', x: 9, y: 6 },
    { name: 'Vancouver', x: 0, y: 5 },
    { name: 'Calgary', x: 2, y: 4 },
    { name: 'Edmonton', x: 1, y: 2 },
    { name: 'Quebec City', x: 9, y: 4 },
    { name: 'Winnipeg', x: 4, y: 5 },
    { name: 'Hamilton', x: 6, y: 8 },
    { name: 'Halifax', x: 9, y: 8 },
    { name: 'Victoria', x: 0, y: 6 },
    { name: 'Regina', x: 3, y: 4 },
    { name: 'Saskatoon', x: 2, y: 3 },
    { name: 'St Johns', x: 9, y: 9 },
    { name: 'Yellowknife', x: 3, y: 0 },
  ],

  [Country.AUSTRALIA]: [
    { name: 'Canberra', x: 7, y: 6, isCapital: true },
    { name: 'Sydney', x: 9, y: 6 },
    { name: 'Melbourne', x: 5, y: 9 },
    { name: 'Brisbane', x: 9, y: 3 },
    { name: 'Perth', x: 0, y: 6 },
    { name: 'Adelaide', x: 3, y: 8 },
    { name: 'Gold Coast', x: 9, y: 4 },
    { name: 'Newcastle', x: 9, y: 5 },
    { name: 'Darwin', x: 5, y: 0 },
    { name: 'Hobart', x: 6, y: 9 },
    { name: 'Cairns', x: 8, y: 1 },
    { name: 'Townsville', x: 9, y: 2 },
    { name: 'Alice Springs', x: 4, y: 4 },
    { name: 'Geelong', x: 4, y: 9 },
    { name: 'Wollongong', x: 8, y: 7 },
  ],

  [Country.ITALY]: [
    { name: 'Rome', x: 5, y: 6, isCapital: true },
    { name: 'Milan', x: 2, y: 1 },
    { name: 'Naples', x: 6, y: 8 },
    { name: 'Turin', x: 1, y: 1 },
    { name: 'Palermo', x: 2, y: 9 },
    { name: 'Genoa', x: 1, y: 2 },
    { name: 'Bologna', x: 4, y: 3 },
    { name: 'Florence', x: 4, y: 5 },
    { name: 'Venice', x: 6, y: 1 },
    { name: 'Bari', x: 7, y: 8 },
    { name: 'Catania', x: 4, y: 9 },
    { name: 'Verona', x: 5, y: 2 },
    { name: 'Messina', x: 6, y: 9 },
    { name: 'Trieste', x: 7, y: 1 },
    { name: 'Cagliari', x: 1, y: 8 },
  ],

  [Country.SPAIN]: [
    { name: 'Madrid', x: 5, y: 5, isCapital: true },
    { name: 'Barcelona', x: 8, y: 2 },
    { name: 'Valencia', x: 7, y: 6 },
    { name: 'Seville', x: 1, y: 8 },
    { name: 'Zaragoza', x: 6, y: 3 },
    { name: 'Malaga', x: 2, y: 9 },
    { name: 'Bilbao', x: 4, y: 0 },
    { name: 'Murcia', x: 6, y: 7 },
    { name: 'Palma', x: 9, y: 5 },
    { name: 'Las Palmas', x: 0, y: 6 },
    { name: 'Valladolid', x: 3, y: 2 },
    { name: 'Cordoba', x: 2, y: 7 },
    { name: 'Vigo', x: 0, y: 2 },
    { name: 'Granada', x: 3, y: 8 },
    { name: 'Toledo', x: 4, y: 6 },
  ],

  [Country.SOUTH_KOREA]: [
    { name: 'Seoul', x: 5, y: 3, isCapital: true },
    { name: 'Busan', x: 7, y: 9 },
    { name: 'Incheon', x: 3, y: 2 },
    { name: 'Daegu', x: 6, y: 7 },
    { name: 'Daejeon', x: 4, y: 5 },
    { name: 'Gwangju', x: 1, y: 8 },
    { name: 'Suwon', x: 5, y: 4 },
    { name: 'Ulsan', x: 8, y: 8 },
    { name: 'Changwon', x: 6, y: 9 },
    { name: 'Goyang', x: 4, y: 1 },
    { name: 'Yongin', x: 6, y: 4 },
    { name: 'Seongnam', x: 6, y: 3 },
    { name: 'Jeju', x: 2, y: 9 },
    { name: 'Jeonju', x: 2, y: 6 },
    { name: 'Pyongyang', x: 5, y: 0 }, // North Korea reference
  ],

  [Country.MEXICO]: [
    { name: 'Mexico City', x: 5, y: 6, isCapital: true },
    { name: 'Guadalajara', x: 1, y: 5 },
    { name: 'Monterrey', x: 5, y: 1 },
    { name: 'Puebla', x: 6, y: 6 },
    { name: 'Tijuana', x: 0, y: 0 },
    { name: 'Leon', x: 3, y: 4 },
    { name: 'Juarez', x: 2, y: 0 },
    { name: 'Zapopan', x: 0, y: 5 },
    { name: 'Cancun', x: 9, y: 4 },
    { name: 'Merida', x: 7, y: 4 },
    { name: 'Queretaro', x: 4, y: 5 },
    { name: 'Veracruz', x: 7, y: 6 },
    { name: 'Acapulco', x: 1, y: 9 },
    { name: 'Toluca', x: 4, y: 7 },
    { name: 'Hermosillo', x: 0, y: 2 },
  ],

  [Country.TURKEY]: [
    { name: 'Ankara', x: 5, y: 4, isCapital: true },
    { name: 'Istanbul', x: 0, y: 3 },
    { name: 'Izmir', x: 0, y: 6 },
    { name: 'Bursa', x: 1, y: 2 },
    { name: 'Antalya', x: 1, y: 8 },
    { name: 'Adana', x: 6, y: 8 },
    { name: 'Konya', x: 3, y: 6 },
    { name: 'Gaziantep', x: 7, y: 7 },
    { name: 'Mersin', x: 4, y: 8 },
    { name: 'Diyarbakir', x: 8, y: 5 },
    { name: 'Kayseri', x: 5, y: 5 },
    { name: 'Eskisehir', x: 2, y: 3 },
    { name: 'Trabzon', x: 7, y: 1 },
    { name: 'Erzurum', x: 8, y: 3 },
    { name: 'Van', x: 9, y: 4 },
  ],

  [Country.SAUDI_ARABIA]: [
    { name: 'Riyadh', x: 5, y: 4, isCapital: true },
    { name: 'Jeddah', x: 0, y: 5 },
    { name: 'Mecca', x: 1, y: 5 },
    { name: 'Medina', x: 1, y: 2 },
    { name: 'Dammam', x: 9, y: 4 },
    { name: 'Khobar', x: 9, y: 5 },
    { name: 'Dhahran', x: 8, y: 5 },
    { name: 'Tabuk', x: 0, y: 1 },
    { name: 'Buraidah', x: 4, y: 2 },
    { name: 'Khamis Mushait', x: 1, y: 8 },
    { name: 'Hofuf', x: 8, y: 4 },
    { name: 'Taif', x: 2, y: 5 },
    { name: 'Jubail', x: 9, y: 3 },
    { name: 'Hail', x: 3, y: 2 },
    { name: 'Najran', x: 2, y: 9 },
  ],

  [Country.ARGENTINA]: [
    { name: 'Buenos Aires', x: 7, y: 5, isCapital: true },
    { name: 'Cordoba', x: 4, y: 2 },
    { name: 'Rosario', x: 6, y: 5 },
    { name: 'Mendoza', x: 1, y: 4 },
    { name: 'La Plata', x: 8, y: 5 },
    { name: 'San Miguel de Tucuman', x: 3, y: 1 },
    { name: 'Mar del Plata', x: 8, y: 7 },
    { name: 'Salta', x: 2, y: 0 },
    { name: 'Santa Fe', x: 5, y: 3 },
    { name: 'San Juan', x: 0, y: 3 },
    { name: 'Neuquen', x: 1, y: 7 },
    { name: 'Resistencia', x: 6, y: 1 },
    { name: 'Bariloche', x: 0, y: 8 },
    { name: 'Ushuaia', x: 1, y: 9 },
    { name: 'Comodoro Rivadavia', x: 2, y: 9 },
  ],

  [Country.POLAND]: [
    { name: 'Warsaw', x: 6, y: 4, isCapital: true },
    { name: 'Krakow', x: 5, y: 9 },
    { name: 'Lodz', x: 4, y: 5 },
    { name: 'Wroclaw', x: 1, y: 6 },
    { name: 'Poznan', x: 1, y: 3 },
    { name: 'Gdansk', x: 4, y: 0 },
    { name: 'Szczecin', x: 0, y: 1 },
    { name: 'Bydgoszcz', x: 3, y: 1 },
    { name: 'Lublin', x: 8, y: 5 },
    { name: 'Katowice', x: 3, y: 9 },
    { name: 'Bialystok', x: 9, y: 2 },
    { name: 'Gdynia', x: 5, y: 0 },
    { name: 'Czestochowa', x: 3, y: 7 },
    { name: 'Radom', x: 7, y: 5 },
    { name: 'Torun', x: 4, y: 2 },
  ],

  [Country.EGYPT]: [
    { name: 'Cairo', x: 5, y: 4, isCapital: true },
    { name: 'Alexandria', x: 2, y: 2 },
    { name: 'Giza', x: 4, y: 4 },
    { name: 'Shubra El Kheima', x: 6, y: 3 },
    { name: 'Port Said', x: 7, y: 2 },
    { name: 'Suez', x: 7, y: 4 },
    { name: 'Luxor', x: 5, y: 7 },
    { name: 'Aswan', x: 5, y: 9 },
    { name: 'Mansoura', x: 3, y: 2 },
    { name: 'Tanta', x: 3, y: 1 },
    { name: 'Asyut', x: 4, y: 6 },
    { name: 'Ismailia', x: 7, y: 3 },
    { name: 'Hurghada', x: 9, y: 6 },
    { name: 'Sharm El Sheikh', x: 9, y: 8 },
    { name: 'Minya', x: 3, y: 5 },
  ],

  [Country.INDONESIA]: [
    { name: 'Jakarta', x: 1, y: 6, isCapital: true },
    { name: 'Surabaya', x: 5, y: 7 },
    { name: 'Bandung', x: 1, y: 7 },
    { name: 'Medan', x: 0, y: 2 },
    { name: 'Semarang', x: 3, y: 6 },
    { name: 'Makassar', x: 7, y: 9 },
    { name: 'Palembang', x: 1, y: 4 },
    { name: 'Tangerang', x: 0, y: 6 },
    { name: 'Depok', x: 2, y: 5 },
    { name: 'Batam', x: 1, y: 3 },
    { name: 'Padang', x: 0, y: 4 },
    { name: 'Denpasar', x: 6, y: 8 },
    { name: 'Manado', x: 8, y: 2 },
    { name: 'Yogyakarta', x: 3, y: 7 },
    { name: 'Balikpapan', x: 7, y: 5 },
  ],

  [Country.SOUTH_AFRICA]: [
    { name: 'Pretoria', x: 6, y: 4, isCapital: true },
    { name: 'Cape Town', x: 1, y: 9 },
    { name: 'Johannesburg', x: 5, y: 5 },
    { name: 'Durban', x: 8, y: 6 },
    { name: 'Soweto', x: 4, y: 5 },
    { name: 'Port Elizabeth', x: 3, y: 9 },
    { name: 'Pietermaritzburg', x: 7, y: 7 },
    { name: 'East London', x: 5, y: 9 },
    { name: 'Bloemfontein', x: 4, y: 7 },
    { name: 'Nelspruit', x: 8, y: 3 },
    { name: 'Kimberley', x: 2, y: 7 },
    { name: 'Polokwane', x: 7, y: 1 },
    { name: 'George', x: 2, y: 9 },
    { name: 'Rustenburg', x: 4, y: 3 },
    { name: 'Richards Bay', x: 9, y: 5 },
  ],

  [Country.NIGERIA]: [
    { name: 'Abuja', x: 5, y: 5, isCapital: true },
    { name: 'Lagos', x: 1, y: 8 },
    { name: 'Kano', x: 5, y: 0 },
    { name: 'Ibadan', x: 1, y: 6 },
    { name: 'Kaduna', x: 5, y: 2 },
    { name: 'Port Harcourt', x: 2, y: 9 },
    { name: 'Benin City', x: 2, y: 7 },
    { name: 'Maiduguri', x: 8, y: 1 },
    { name: 'Zaria', x: 6, y: 2 },
    { name: 'Jos', x: 6, y: 3 },
    { name: 'Ilorin', x: 3, y: 5 },
    { name: 'Aba', x: 1, y: 9 },
    { name: 'Enugu', x: 4, y: 8 },
    { name: 'Sokoto', x: 2, y: 0 },
    { name: 'Calabar', x: 3, y: 9 },
  ],

  [Country.DENMARK]: [
    { name: 'Copenhagen', x: 6, y: 5, isCapital: true },
    { name: 'Aarhus', x: 2, y: 4 },
    { name: 'Odense', x: 4, y: 8 },
    { name: 'Aalborg', x: 3, y: 0 },
    { name: 'Esbjerg', x: 0, y: 5 },
    { name: 'Randers', x: 4, y: 2 },
    { name: 'Kolding', x: 2, y: 7 },
    { name: 'Horsens', x: 2, y: 5 },
    { name: 'Vejle', x: 1, y: 6 },
    { name: 'Roskilde', x: 5, y: 6 },
    { name: 'Herning', x: 1, y: 3 },
    { name: 'Helsingor', x: 7, y: 4 },
  ],

  [Country.ESTONIA]: [
    { name: 'Tallinn', x: 4, y: 2, isCapital: true },
    { name: 'Tartu', x: 6, y: 8 },
    { name: 'Narva', x: 9, y: 3 },
    { name: 'Parnu', x: 1, y: 6 },
    { name: 'Kohtla-Jarve', x: 8, y: 3 },
    { name: 'Viljandi', x: 3, y: 7 },
    { name: 'Rakvere', x: 6, y: 2 },
    { name: 'Maardu', x: 5, y: 2 },
    { name: 'Kuressaare', x: 0, y: 5 },
    { name: 'Sillamae', x: 9, y: 2 },
    { name: 'Valga', x: 4, y: 9 },
    { name: 'Haapsalu', x: 0, y: 3 },
  ],

  [Country.UKRAINE]: [
    { name: 'Kyiv', x: 5, y: 3, isCapital: true },
    { name: 'Kharkiv', x: 8, y: 2 },
    { name: 'Odesa', x: 3, y: 9 },
    { name: 'Dnipro', x: 7, y: 5 },
    { name: 'Donetsk', x: 9, y: 5 },
    { name: 'Zaporizhzhia', x: 7, y: 7 },
    { name: 'Lviv', x: 0, y: 3 },
    { name: 'Kryvyi Rih', x: 5, y: 7 },
    { name: 'Mykolaiv', x: 4, y: 8 },
    { name: 'Mariupol', x: 8, y: 6 },
    { name: 'Luhansk', x: 9, y: 4 },
    { name: 'Vinnytsia', x: 3, y: 4 },
    { name: 'Simferopol', x: 5, y: 9 },
    { name: 'Chernihiv', x: 5, y: 0 },
    { name: 'Poltava', x: 6, y: 4 },
  ],

  [Country.NETHERLANDS]: [
    { name: 'Amsterdam', x: 4, y: 2, isCapital: true },
    { name: 'Rotterdam', x: 2, y: 6 },
    { name: 'The Hague', x: 2, y: 4 },
    { name: 'Utrecht', x: 4, y: 4 },
    { name: 'Eindhoven', x: 4, y: 8 },
    { name: 'Groningen', x: 6, y: 0 },
    { name: 'Tilburg', x: 3, y: 7 },
    { name: 'Almere', x: 5, y: 2 },
    { name: 'Breda', x: 2, y: 8 },
    { name: 'Nijmegen', x: 6, y: 5 },
    { name: 'Apeldoorn', x: 6, y: 3 },
    { name: 'Arnhem', x: 7, y: 5 },
    { name: 'Haarlem', x: 3, y: 1 },
    { name: 'Enschede', x: 8, y: 3 },
    { name: 'Maastricht', x: 4, y: 9 },
  ],

  [Country.SWEDEN]: [
    { name: 'Stockholm', x: 6, y: 5, isCapital: true },
    { name: 'Gothenburg', x: 1, y: 6 },
    { name: 'Malmo', x: 2, y: 9 },
    { name: 'Uppsala', x: 6, y: 3 },
    { name: 'Vasteras', x: 4, y: 4 },
    { name: 'Orebro', x: 3, y: 6 },
    { name: 'Linkoping', x: 4, y: 8 },
    { name: 'Helsingborg', x: 2, y: 8 },
    { name: 'Jonkoping', x: 2, y: 7 },
    { name: 'Norrkoping', x: 5, y: 7 },
    { name: 'Lund', x: 1, y: 9 },
    { name: 'Umea', x: 7, y: 0 },
    { name: 'Gavle', x: 6, y: 2 },
    { name: 'Boras', x: 1, y: 7 },
    { name: 'Sundsvall', x: 7, y: 1 },
  ],

  [Country.ISRAEL]: [
    { name: 'Jerusalem', x: 5, y: 5, isCapital: true },
    { name: 'Tel Aviv', x: 2, y: 4 },
    { name: 'Haifa', x: 4, y: 0 },
    { name: 'Rishon LeZion', x: 2, y: 5 },
    { name: 'Petah Tikva', x: 3, y: 3 },
    { name: 'Ashdod', x: 1, y: 6 },
    { name: 'Netanya', x: 3, y: 2 },
    { name: 'Beer Sheva', x: 2, y: 8 },
    { name: 'Holon', x: 1, y: 4 },
    { name: 'Bnei Brak', x: 4, y: 3 },
    { name: 'Ramat Gan', x: 1, y: 3 },
    { name: 'Ashkelon', x: 0, y: 6 },
    { name: 'Rehovot', x: 1, y: 7 },
    { name: 'Herzliya', x: 3, y: 1 },
    { name: 'Eilat', x: 4, y: 9 },
  ],

  [Country.BELGIUM]: [
    { name: 'Brussels', x: 5, y: 5, isCapital: true },
    { name: 'Antwerp', x: 5, y: 1 },
    { name: 'Ghent', x: 1, y: 3 },
    { name: 'Charleroi', x: 4, y: 8 },
    { name: 'Liege', x: 7, y: 5 },
    { name: 'Bruges', x: 0, y: 2 },
    { name: 'Namur', x: 6, y: 7 },
    { name: 'Leuven', x: 6, y: 4 },
    { name: 'Mons', x: 2, y: 8 },
    { name: 'Mechelen', x: 6, y: 2 },
    { name: 'Aalst', x: 2, y: 4 },
    { name: 'Hasselt', x: 7, y: 3 },
  ],

  [Country.SWITZERLAND]: [
    { name: 'Bern', x: 3, y: 5, isCapital: true },
    { name: 'Zurich', x: 6, y: 2 },
    { name: 'Geneva', x: 0, y: 7 },
    { name: 'Basel', x: 4, y: 1 },
    { name: 'Lausanne', x: 1, y: 6 },
    { name: 'Winterthur', x: 6, y: 1 },
    { name: 'Lucerne', x: 4, y: 4 },
    { name: 'St. Gallen', x: 7, y: 3 },
    { name: 'Lugano', x: 5, y: 9 },
    { name: 'Biel', x: 2, y: 4 },
    { name: 'Thun', x: 2, y: 6 },
    { name: 'Chur', x: 7, y: 5 },
  ],

  [Country.AUSTRIA]: [
    { name: 'Vienna', x: 7, y: 4, isCapital: true },
    { name: 'Graz', x: 5, y: 8 },
    { name: 'Linz', x: 4, y: 2 },
    { name: 'Salzburg', x: 2, y: 4 },
    { name: 'Innsbruck', x: 0, y: 4 },
    { name: 'Klagenfurt', x: 3, y: 9 },
    { name: 'Villach', x: 2, y: 9 },
    { name: 'Wels', x: 4, y: 3 },
    { name: 'St. Polten', x: 7, y: 3 },
    { name: 'Dornbirn', x: 0, y: 5 },
    { name: 'Wiener Neustadt', x: 7, y: 5 },
    { name: 'Steyr', x: 5, y: 3 },
  ],

  [Country.NORWAY]: [
    { name: 'Oslo', x: 5, y: 6, isCapital: true },
    { name: 'Bergen', x: 0, y: 5 },
    { name: 'Trondheim', x: 4, y: 2 },
    { name: 'Stavanger', x: 0, y: 8 },
    { name: 'Drammen', x: 4, y: 7 },
    { name: 'Fredrikstad', x: 6, y: 8 },
    { name: 'Kristiansand', x: 1, y: 9 },
    { name: 'Tromso', x: 6, y: 0 },
    { name: 'Sandnes', x: 0, y: 7 },
    { name: 'Asker', x: 4, y: 6 },
    { name: 'Sarpsborg', x: 6, y: 9 },
    { name: 'Skien', x: 2, y: 8 },
  ],

  [Country.FINLAND]: [
    { name: 'Helsinki', x: 5, y: 8, isCapital: true },
    { name: 'Espoo', x: 4, y: 8 },
    { name: 'Tampere', x: 2, y: 5 },
    { name: 'Vantaa', x: 5, y: 7 },
    { name: 'Oulu', x: 5, y: 0 },
    { name: 'Turku', x: 1, y: 7 },
    { name: 'Jyvaskyla', x: 4, y: 3 },
    { name: 'Lahti', x: 6, y: 6 },
    { name: 'Kuopio', x: 6, y: 2 },
    { name: 'Pori', x: 1, y: 5 },
    { name: 'Joensuu', x: 8, y: 3 },
    { name: 'Lappeenranta', x: 7, y: 7 },
  ],

  [Country.GREECE]: [
    { name: 'Athens', x: 5, y: 6, isCapital: true },
    { name: 'Thessaloniki', x: 4, y: 0 },
    { name: 'Patras', x: 1, y: 5 },
    { name: 'Heraklion', x: 5, y: 9 },
    { name: 'Larissa', x: 4, y: 2 },
    { name: 'Volos', x: 6, y: 3 },
    { name: 'Rhodes', x: 8, y: 8 },
    { name: 'Ioannina', x: 1, y: 2 },
    { name: 'Chania', x: 3, y: 9 },
    { name: 'Chalcis', x: 6, y: 5 },
    { name: 'Agrinio', x: 1, y: 3 },
    { name: 'Katerini', x: 4, y: 1 },
  ],

  [Country.PORTUGAL]: [
    { name: 'Lisbon', x: 2, y: 6, isCapital: true },
    { name: 'Porto', x: 2, y: 1 },
    { name: 'Vila Nova de Gaia', x: 1, y: 1 },
    { name: 'Amadora', x: 1, y: 6 },
    { name: 'Braga', x: 2, y: 0 },
    { name: 'Coimbra', x: 1, y: 3 },
    { name: 'Funchal', x: 0, y: 8 },
    { name: 'Setubal', x: 2, y: 8 },
    { name: 'Almada', x: 3, y: 7 },
    { name: 'Agualva-Cacem', x: 1, y: 5 },
    { name: 'Faro', x: 3, y: 9 },
    { name: 'Aveiro', x: 0, y: 2 },
  ],

  [Country.IRAN]: [
    { name: 'Tehran', x: 5, y: 3, isCapital: true },
    { name: 'Mashhad', x: 9, y: 2 },
    { name: 'Isfahan', x: 5, y: 5 },
    { name: 'Shiraz', x: 6, y: 8 },
    { name: 'Tabriz', x: 1, y: 1 },
    { name: 'Ahvaz', x: 3, y: 7 },
    { name: 'Qom', x: 5, y: 4 },
    { name: 'Kermanshah', x: 2, y: 4 },
    { name: 'Urmia', x: 0, y: 2 },
    { name: 'Rasht', x: 3, y: 1 },
    { name: 'Kerman', x: 8, y: 7 },
    { name: 'Hamadan', x: 3, y: 3 },
    { name: 'Yazd', x: 7, y: 6 },
    { name: 'Zahedan', x: 9, y: 8 },
    { name: 'Bushehr', x: 4, y: 9 },
    { name: 'Abadan', x: 2, y: 8 },
    { name: 'Kashan', x: 6, y: 4 },
    { name: 'Sari', x: 6, y: 1 },
    { name: 'Gorgan', x: 7, y: 0 },
    { name: 'Bandar Abbas', x: 7, y: 9 },
  ],

  [Country.IRAQ]: [
    { name: 'Baghdad', x: 5, y: 5, isCapital: true },
    { name: 'Basra', x: 6, y: 9 },
    { name: 'Mosul', x: 4, y: 0 },
    { name: 'Erbil', x: 5, y: 1 },
    { name: 'Najaf', x: 4, y: 7 },
    { name: 'Karbala', x: 3, y: 6 },
    { name: 'Kirkuk', x: 6, y: 2 },
    { name: 'Sulaymaniyah', x: 7, y: 1 },
    { name: 'Ramadi', x: 3, y: 4 },
    { name: 'Fallujah', x: 4, y: 4 },
    { name: 'Nasiriyah', x: 5, y: 8 },
    { name: 'Amarah', x: 7, y: 7 },
    { name: 'Tikrit', x: 5, y: 3 },
    { name: 'Samarra', x: 4, y: 3 },
    { name: 'Hillah', x: 4, y: 6 },
    { name: 'Kut', x: 6, y: 6 },
    { name: 'Dohuk', x: 3, y: 0 },
    { name: 'Zakho', x: 2, y: 0 },
  ],

  [Country.SUDAN]: [
    { name: 'Khartoum', x: 5, y: 4, isCapital: true },
    { name: 'Omdurman', x: 4, y: 4 },
    { name: 'Port Sudan', x: 9, y: 2 },
    { name: 'Kassala', x: 8, y: 3 },
    { name: 'Nyala', x: 1, y: 6 },
    { name: 'El Obeid', x: 3, y: 5 },
    { name: 'Wad Madani', x: 6, y: 5 },
    { name: 'Gedaref', x: 7, y: 4 },
    { name: 'El Fasher', x: 2, y: 5 },
    { name: 'Kosti', x: 5, y: 6 },
    { name: 'Juba', x: 5, y: 9 },
    { name: 'Wau', x: 3, y: 8 },
    { name: 'Malakal', x: 6, y: 8 },
    { name: 'Atbara', x: 7, y: 2 },
    { name: 'Dongola', x: 6, y: 1 },
    { name: 'Rabak', x: 4, y: 6 },
    { name: 'Ed Daein', x: 2, y: 7 },
    { name: 'El Geneina', x: 0, y: 5 },
    { name: 'Kadugli', x: 3, y: 7 },
    { name: 'Wadi Halfa', x: 7, y: 0 },
  ],

  [Country.PAKISTAN]: [
    { name: 'Islamabad', x: 5, y: 2, isCapital: true },
    { name: 'Karachi', x: 3, y: 9 },
    { name: 'Lahore', x: 6, y: 3 },
    { name: 'Faisalabad', x: 5, y: 4 },
    { name: 'Rawalpindi', x: 5, y: 1 },
    { name: 'Peshawar', x: 4, y: 1 },
    { name: 'Multan', x: 4, y: 6 },
    { name: 'Hyderabad', x: 3, y: 8 },
    { name: 'Quetta', x: 1, y: 5 },
    { name: 'Bahawalpur', x: 5, y: 7 },
    { name: 'Sargodha', x: 5, y: 3 },
    { name: 'Sialkot', x: 7, y: 2 },
    { name: 'Sukkur', x: 3, y: 7 },
    { name: 'Larkana', x: 2, y: 7 },
    { name: 'Gujranwala', x: 6, y: 2 },
    { name: 'Dera Ghazi Khan', x: 3, y: 5 },
    { name: 'Mardan', x: 4, y: 0 },
    { name: 'Gwadar', x: 0, y: 9 },
    { name: 'Gilgit', x: 7, y: 0 },
    { name: 'Mirpur Khas', x: 4, y: 8 },
  ],

  [Country.LITHUANIA]: [
    { name: 'Vilnius', x: 7, y: 6, isCapital: true },
    { name: 'Kaunas', x: 4, y: 5 },
    { name: 'Klaipeda', x: 0, y: 3 },
    { name: 'Siauliai', x: 3, y: 2 },
    { name: 'Panevezys', x: 5, y: 3 },
    { name: 'Alytus', x: 5, y: 8 },
    { name: 'Marijampole', x: 3, y: 7 },
    { name: 'Mazeikiai', x: 1, y: 1 },
    { name: 'Jonava', x: 5, y: 5 },
    { name: 'Utena', x: 7, y: 3 },
    { name: 'Kedainiai', x: 4, y: 4 },
    { name: 'Telsiai', x: 1, y: 2 },
    { name: 'Visaginas', x: 9, y: 4 },
    { name: 'Taurage', x: 1, y: 5 },
    { name: 'Ukmerge', x: 6, y: 4 },
    { name: 'Plunge', x: 0, y: 1 },
    { name: 'Palanga', x: 0, y: 2 },
    { name: 'Kretinga', x: 0, y: 4 },
    { name: 'Radviliskis', x: 3, y: 3 },
    { name: 'Druskininkai', x: 6, y: 9 },
  ],

  [Country.LATVIA]: [
    { name: 'Riga', x: 5, y: 5, isCapital: true },
    { name: 'Daugavpils', x: 8, y: 8 },
    { name: 'Liepaja', x: 0, y: 6 },
    { name: 'Jelgava', x: 3, y: 6 },
    { name: 'Jurmala', x: 4, y: 4 },
    { name: 'Ventspils', x: 0, y: 3 },
    { name: 'Rezekne', x: 9, y: 6 },
    { name: 'Valmiera', x: 6, y: 2 },
    { name: 'Jekabpils', x: 7, y: 7 },
    { name: 'Ogre', x: 6, y: 5 },
    { name: 'Tukums', x: 2, y: 5 },
    { name: 'Salaspils', x: 5, y: 6 },
    { name: 'Cesis', x: 6, y: 3 },
    { name: 'Olaine', x: 4, y: 6 },
    { name: 'Kuldiga', x: 1, y: 4 },
    { name: 'Saldus', x: 1, y: 7 },
    { name: 'Talsi', x: 1, y: 2 },
    { name: 'Dobele', x: 2, y: 7 },
    { name: 'Krustpils', x: 7, y: 6 },
    { name: 'Sigulda', x: 5, y: 3 },
  ],
}
