import { Country } from './Countries.ts'

// Define city neighbor connections for each country
// Rules:
// 1. All cities must be connected in a single network
// 2. Each city has at least 2 neighbors
// 3. No more than 3 neighbors in the same direction (N/S/E/W)
// 4. No connections that would cross over a third city

export type CityNeighbors = Record<string, string[]>

export const CountryCityNeighbors: Partial<Record<Country, CityNeighbors>> = {
  [Country.USA]: {
    'Washington DC': ['Philadelphia', 'Atlanta', 'Chicago', 'Denver'],
    'New York': ['Boston', 'Philadelphia', 'Detroit'],
    'Los Angeles': ['San Francisco', 'San Diego', 'Las Vegas', 'Phoenix'],
    Chicago: ['Detroit', 'Denver', 'Washington DC'],
    Houston: ['Dallas', 'New Orleans', 'San Antonio'],
    Phoenix: ['Los Angeles', 'Las Vegas', 'San Antonio'],
    Philadelphia: ['New York', 'Washington DC'],
    'San Antonio': ['Phoenix', 'Houston', 'Dallas'],
    'San Diego': ['Los Angeles'],
    Dallas: ['Houston', 'San Antonio', 'Denver', 'Atlanta'],
    'San Francisco': ['Los Angeles', 'Portland'],
    Seattle: ['Portland'],
    Denver: ['Chicago', 'Dallas', 'Las Vegas', 'Washington DC'],
    Boston: ['New York'],
    Miami: ['Atlanta', 'New Orleans'],
    Atlanta: ['Washington DC', 'Dallas', 'Miami'],
    Detroit: ['New York', 'Chicago'],
    'Las Vegas': ['Los Angeles', 'Phoenix', 'Denver'],
    Portland: ['Seattle', 'San Francisco'],
    'New Orleans': ['Houston', 'Miami'],
  },

  [Country.CHINA]: {
    Beijing: ['Tianjin', 'Xian', 'Shanghai', 'Shenyang', 'Zhengzhou'],
    Shanghai: ['Beijing', 'Nanjing', 'Hangzhou', 'Wuhan', 'Suzhou'],
    Guangzhou: ['Shenzhen', 'Wuhan', 'Chengdu'],
    Shenzhen: ['Guangzhou', 'Suzhou'],
    Chengdu: ['Guangzhou', 'Chongqing', 'Xian', 'Kunming'],
    Tianjin: ['Beijing', 'Shenyang', 'Qingdao'],
    Wuhan: ['Shanghai', 'Guangzhou', 'Xian', 'Nanjing', 'Zhengzhou'],
    Chongqing: ['Chengdu', 'Xian'],
    Nanjing: ['Shanghai', 'Wuhan', 'Hangzhou'],
    Xian: ['Beijing', 'Chengdu', 'Chongqing', 'Wuhan', 'Urumqi'],
    Hangzhou: ['Shanghai', 'Nanjing', 'Suzhou'],
    Suzhou: ['Hangzhou', 'Shanghai', 'Shenzhen'],
    Zhengzhou: ['Beijing', 'Wuhan'],
    Harbin: ['Shenyang', 'Dalian'],
    Shenyang: ['Beijing', 'Tianjin', 'Harbin', 'Dalian'],
    Dalian: ['Shenyang', 'Harbin', 'Qingdao'],
    Qingdao: ['Dalian', 'Tianjin'],
    Urumqi: ['Xian', 'Lhasa'],
    Kunming: ['Chengdu', 'Lhasa'],
    Lhasa: ['Kunming', 'Urumqi'],
  },

  [Country.GERMANY]: {
    Berlin: ['Hamburg', 'Leipzig', 'Munich', 'Hannover', 'Dresden'],
    Hamburg: ['Berlin', 'Bremen', 'Hannover'],
    Munich: ['Berlin', 'Stuttgart', 'Nuremberg'],
    Cologne: ['Dusseldorf', 'Bonn'],
    Frankfurt: ['Stuttgart', 'Nuremberg', 'Leipzig', 'Bonn'],
    Stuttgart: ['Munich', 'Frankfurt', 'Nuremberg'],
    Dusseldorf: ['Cologne', 'Essen', 'Dortmund'],
    Dortmund: ['Dusseldorf', 'Essen'],
    Leipzig: ['Berlin', 'Frankfurt', 'Dresden'],
    Dresden: ['Leipzig', 'Berlin'],
    Bremen: ['Hamburg', 'Hannover'],
    Hannover: ['Berlin', 'Hamburg', 'Bremen'],
    Nuremberg: ['Munich', 'Frankfurt', 'Stuttgart'],
    Essen: ['Dusseldorf', 'Dortmund'],
    Bonn: ['Cologne', 'Frankfurt'],
  },

  [Country.FRANCE]: {
    Paris: ['Lyon', 'Lille', 'Reims', 'Le Havre'],
    Marseille: ['Lyon', 'Nice', 'Montpellier'],
    Lyon: ['Paris', 'Marseille', 'Grenoble', 'Saint-Etienne', 'Strasbourg'],
    Toulouse: ['Bordeaux', 'Montpellier'],
    Nice: ['Marseille', 'Grenoble'],
    Nantes: ['Rennes', 'Bordeaux', 'Le Havre'],
    Strasbourg: ['Reims', 'Lyon'],
    Bordeaux: ['Toulouse', 'Nantes'],
    Lille: ['Paris', 'Reims'],
    Rennes: ['Nantes', 'Le Havre'],
    Reims: ['Paris', 'Lille', 'Strasbourg'],
    Montpellier: ['Marseille', 'Toulouse'],
    'Saint-Etienne': ['Lyon', 'Grenoble'],
    'Le Havre': ['Paris', 'Nantes', 'Rennes'],
    Grenoble: ['Lyon', 'Nice', 'Saint-Etienne'],
  },

  [Country.UK]: {
    London: ['Birmingham', 'Bristol', 'Southampton'],
    Birmingham: ['London', 'Manchester', 'Nottingham'],
    Manchester: ['Birmingham', 'Liverpool', 'Leeds', 'Sheffield'],
    Glasgow: ['Edinburgh', 'Belfast'],
    Liverpool: ['Manchester', 'Sheffield', 'Cardiff'],
    Edinburgh: ['Glasgow', 'Newcastle', 'Aberdeen'],
    Leeds: ['Manchester', 'Sheffield', 'Newcastle'],
    Sheffield: ['Manchester', 'Leeds', 'Liverpool', 'Nottingham'],
    Bristol: ['London', 'Cardiff', 'Southampton'],
    Newcastle: ['Edinburgh', 'Leeds'],
    Cardiff: ['Bristol', 'Liverpool', 'Belfast'],
    Belfast: ['Glasgow', 'Cardiff'],
    Nottingham: ['Birmingham', 'Sheffield'],
    Southampton: ['London', 'Bristol'],
    Aberdeen: ['Edinburgh'],
  },

  [Country.JAPAN]: {
    Tokyo: ['Yokohama', 'Kawasaki', 'Saitama', 'Chiba', 'Sendai', 'Shizuoka'],
    Osaka: ['Kyoto', 'Kobe', 'Nagoya'],
    Yokohama: ['Tokyo', 'Kawasaki'],
    Nagoya: ['Osaka', 'Kyoto', 'Shizuoka', 'Niigata'],
    Sapporo: ['Sendai'],
    Kobe: ['Osaka', 'Okayama'],
    Kyoto: ['Osaka', 'Nagoya'],
    Fukuoka: ['Kitakyushu', 'Kumamoto', 'Naha'],
    Kawasaki: ['Tokyo', 'Yokohama'],
    Saitama: ['Tokyo'],
    Hiroshima: ['Okayama', 'Kitakyushu'],
    Sendai: ['Tokyo', 'Sapporo', 'Niigata'],
    Chiba: ['Tokyo'],
    Kitakyushu: ['Fukuoka', 'Hiroshima'],
    Niigata: ['Sendai', 'Nagoya'],
    Naha: ['Fukuoka'],
    Shizuoka: ['Nagoya', 'Tokyo'],
    Kumamoto: ['Fukuoka', 'Nagasaki'],
    Okayama: ['Kobe', 'Hiroshima'],
    Nagasaki: ['Kumamoto'],
  },

  [Country.RUSSIA]: {
    Moscow: ['St Petersburg', 'Nizhny Novgorod', 'Kazan', 'Volgograd', 'Yekaterinburg'],
    'St Petersburg': ['Moscow', 'Kaliningrad', 'Murmansk'],
    Novosibirsk: ['Yekaterinburg', 'Omsk', 'Krasnoyarsk', 'Chelyabinsk'],
    Yekaterinburg: ['Moscow', 'Novosibirsk', 'Chelyabinsk', 'Perm', 'Ufa'],
    Vladivostok: ['Khabarovsk', 'Irkutsk'],
    'Nizhny Novgorod': ['Moscow', 'Kazan', 'Samara'],
    Volgograd: ['Moscow', 'Rostov-on-Don', 'Samara'],
    'Rostov-on-Don': ['Volgograd', 'Sochi'],
    Kazan: ['Moscow', 'Nizhny Novgorod', 'Perm', 'Ufa'],
    Omsk: ['Novosibirsk', 'Chelyabinsk', 'Krasnoyarsk'],
    Samara: ['Nizhny Novgorod', 'Volgograd', 'Chelyabinsk'],
    Chelyabinsk: ['Yekaterinburg', 'Novosibirsk', 'Omsk', 'Samara', 'Ufa'],
    Kaliningrad: ['St Petersburg'],
    Krasnoyarsk: ['Novosibirsk', 'Omsk', 'Irkutsk'],
    Irkutsk: ['Krasnoyarsk', 'Vladivostok', 'Khabarovsk'],
    Khabarovsk: ['Irkutsk', 'Vladivostok'],
    Murmansk: ['St Petersburg'],
    Sochi: ['Rostov-on-Don'],
    Perm: ['Yekaterinburg', 'Kazan', 'Ufa'],
    Ufa: ['Yekaterinburg', 'Kazan', 'Perm', 'Chelyabinsk'],
  },

  [Country.INDIA]: {
    'New Delhi': ['Jaipur', 'Lucknow', 'Bhopal', 'Ahmedabad'],
    Mumbai: ['Surat', 'Pune', 'Ahmedabad', 'Bhopal'],
    Bangalore: ['Chennai', 'Hyderabad', 'Kochi'],
    Kolkata: ['Lucknow', 'Patna', 'Varanasi', 'Guwahati'],
    Chennai: ['Bangalore', 'Hyderabad', 'Visakhapatnam'],
    Hyderabad: ['Bangalore', 'Chennai', 'Nagpur', 'Visakhapatnam'],
    Ahmedabad: ['New Delhi', 'Mumbai', 'Surat', 'Jaipur'],
    Pune: ['Mumbai', 'Nagpur'],
    Surat: ['Mumbai', 'Ahmedabad'],
    Jaipur: ['New Delhi', 'Ahmedabad'],
    Lucknow: ['New Delhi', 'Kolkata', 'Kanpur', 'Varanasi'],
    Kanpur: ['Lucknow', 'Patna'],
    Nagpur: ['Pune', 'Hyderabad', 'Bhopal'],
    Patna: ['Kolkata', 'Kanpur', 'Varanasi', 'Guwahati'],
    Bhopal: ['New Delhi', 'Mumbai', 'Nagpur'],
    Kochi: ['Bangalore'],
    Varanasi: ['Kolkata', 'Lucknow', 'Patna'],
    Amritsar: [],
    Guwahati: ['Kolkata', 'Patna'],
    Visakhapatnam: ['Chennai', 'Hyderabad'],
  },

  [Country.BRAZIL]: {
    Brasilia: ['Goiania', 'Belo Horizonte', 'Salvador'],
    'Sao Paulo': ['Rio de Janeiro', 'Belo Horizonte', 'Guarulhos', 'Campinas'],
    'Rio de Janeiro': ['Sao Paulo', 'Belo Horizonte', 'Salvador'],
    Salvador: ['Brasilia', 'Rio de Janeiro', 'Fortaleza', 'Recife'],
    Fortaleza: ['Salvador', 'Recife', 'Natal', 'Belem'],
    'Belo Horizonte': ['Brasilia', 'Sao Paulo', 'Rio de Janeiro', 'Goiania'],
    Manaus: ['Belem'],
    Curitiba: ['Sao Paulo', 'Porto Alegre', 'Guarulhos'],
    Recife: ['Salvador', 'Fortaleza', 'Natal'],
    'Porto Alegre': ['Curitiba', 'Campinas'],
    Belem: ['Manaus', 'Fortaleza'],
    Goiania: ['Brasilia', 'Belo Horizonte', 'Campinas'],
    Guarulhos: ['Sao Paulo', 'Curitiba'],
    Campinas: ['Sao Paulo', 'Porto Alegre', 'Goiania'],
    Natal: ['Fortaleza', 'Recife'],
  },

  [Country.CANADA]: {
    Ottawa: ['Montreal', 'Toronto', 'Quebec City', 'Winnipeg'],
    Toronto: ['Ottawa', 'Montreal', 'Hamilton', 'Winnipeg'],
    Montreal: ['Ottawa', 'Toronto', 'Quebec City', 'Halifax'],
    Vancouver: ['Victoria', 'Calgary', 'Edmonton'],
    Calgary: ['Vancouver', 'Edmonton', 'Regina', 'Winnipeg'],
    Edmonton: ['Vancouver', 'Calgary', 'Saskatoon'],
    'Quebec City': ['Ottawa', 'Montreal', 'Halifax'],
    Winnipeg: ['Ottawa', 'Toronto', 'Calgary', 'Regina'],
    Hamilton: ['Toronto'],
    Halifax: ['Montreal', 'Quebec City', 'St Johns'],
    Victoria: ['Vancouver'],
    Regina: ['Calgary', 'Winnipeg', 'Saskatoon'],
    Saskatoon: ['Edmonton', 'Regina', 'Yellowknife'],
    'St Johns': ['Halifax'],
    Yellowknife: ['Saskatoon'],
  },

  [Country.AUSTRALIA]: {
    Canberra: ['Sydney', 'Melbourne', 'Newcastle'],
    Sydney: ['Canberra', 'Newcastle', 'Brisbane', 'Wollongong'],
    Melbourne: ['Canberra', 'Adelaide', 'Hobart', 'Geelong'],
    Brisbane: ['Sydney', 'Gold Coast', 'Townsville', 'Cairns'],
    Perth: ['Adelaide', 'Darwin'],
    Adelaide: ['Melbourne', 'Perth', 'Alice Springs'],
    'Gold Coast': ['Brisbane', 'Newcastle'],
    Newcastle: ['Sydney', 'Gold Coast', 'Canberra'],
    Darwin: ['Perth', 'Alice Springs', 'Cairns'],
    Hobart: ['Melbourne', 'Geelong'],
    Cairns: ['Brisbane', 'Darwin', 'Townsville'],
    Townsville: ['Brisbane', 'Cairns'],
    'Alice Springs': ['Adelaide', 'Darwin'],
    Geelong: ['Melbourne', 'Hobart'],
    Wollongong: ['Sydney'],
  },

  [Country.ITALY]: {
    Rome: ['Naples', 'Florence', 'Bologna'],
    Milan: ['Turin', 'Bologna', 'Venice', 'Genoa'],
    Naples: ['Rome', 'Bari', 'Palermo'],
    Turin: ['Milan', 'Genoa'],
    Palermo: ['Naples', 'Catania', 'Messina'],
    Genoa: ['Milan', 'Turin', 'Bologna'],
    Bologna: ['Rome', 'Milan', 'Florence', 'Genoa', 'Venice'],
    Florence: ['Rome', 'Bologna'],
    Venice: ['Milan', 'Bologna', 'Verona', 'Trieste'],
    Bari: ['Naples', 'Catania'],
    Catania: ['Palermo', 'Bari', 'Messina'],
    Verona: ['Venice', 'Trieste'],
    Messina: ['Palermo', 'Catania'],
    Trieste: ['Venice', 'Verona'],
    Cagliari: [],
  },

  [Country.SPAIN]: {
    Madrid: ['Barcelona', 'Valencia', 'Seville', 'Valladolid', 'Toledo'],
    Barcelona: ['Madrid', 'Zaragoza', 'Valencia'],
    Valencia: ['Madrid', 'Barcelona', 'Murcia'],
    Seville: ['Madrid', 'Cordoba', 'Granada', 'Malaga'],
    Zaragoza: ['Madrid', 'Barcelona', 'Bilbao'],
    Malaga: ['Seville', 'Granada'],
    Bilbao: ['Zaragoza', 'Valladolid', 'Vigo'],
    Murcia: ['Valencia', 'Granada'],
    Palma: [],
    'Las Palmas': ['Seville'],
    Valladolid: ['Madrid', 'Bilbao'],
    Cordoba: ['Seville', 'Granada'],
    Vigo: ['Bilbao'],
    Granada: ['Seville', 'Cordoba', 'Malaga', 'Murcia'],
    Toledo: ['Madrid'],
  },

  [Country.SOUTH_KOREA]: {
    Seoul: ['Incheon', 'Suwon', 'Daejeon', 'Goyang', 'Seongnam'],
    Busan: ['Daegu', 'Ulsan', 'Changwon'],
    Incheon: ['Seoul', 'Goyang'],
    Daegu: ['Busan', 'Daejeon', 'Ulsan'],
    Daejeon: ['Seoul', 'Daegu', 'Jeonju'],
    Gwangju: ['Jeonju', 'Jeju'],
    Suwon: ['Seoul', 'Yongin'],
    Ulsan: ['Busan', 'Daegu'],
    Changwon: ['Busan'],
    Goyang: ['Seoul', 'Incheon', 'Pyongyang'],
    Yongin: ['Suwon', 'Seongnam'],
    Seongnam: ['Seoul', 'Yongin'],
    Jeju: ['Gwangju'],
    Jeonju: ['Daejeon', 'Gwangju'],
    Pyongyang: ['Goyang'],
  },

  [Country.MEXICO]: {
    'Mexico City': ['Puebla', 'Toluca', 'Queretaro', 'Veracruz'],
    Guadalajara: ['Zapopan', 'Leon', 'Queretaro'],
    Monterrey: ['Leon', 'Juarez'],
    Puebla: ['Mexico City', 'Veracruz'],
    Tijuana: ['Juarez', 'Hermosillo'],
    Leon: ['Guadalajara', 'Monterrey', 'Queretaro'],
    Juarez: ['Monterrey', 'Tijuana', 'Hermosillo'],
    Zapopan: ['Guadalajara'],
    Cancun: ['Merida'],
    Merida: ['Cancun', 'Veracruz'],
    Queretaro: ['Mexico City', 'Guadalajara', 'Leon'],
    Veracruz: ['Mexico City', 'Puebla', 'Merida'],
    Acapulco: ['Toluca'],
    Toluca: ['Mexico City', 'Acapulco'],
    Hermosillo: ['Tijuana', 'Juarez'],
  },

  [Country.TURKEY]: {
    Ankara: ['Istanbul', 'Konya', 'Kayseri', 'Eskisehir'],
    Istanbul: ['Ankara', 'Bursa', 'Eskisehir'],
    Izmir: ['Bursa', 'Antalya', 'Konya'],
    Bursa: ['Istanbul', 'Izmir', 'Eskisehir'],
    Antalya: ['Izmir', 'Konya', 'Mersin'],
    Adana: ['Gaziantep', 'Mersin', 'Kayseri'],
    Konya: ['Ankara', 'Izmir', 'Antalya', 'Kayseri'],
    Gaziantep: ['Adana', 'Diyarbakir', 'Kayseri'],
    Mersin: ['Antalya', 'Adana'],
    Diyarbakir: ['Gaziantep', 'Erzurum', 'Van'],
    Kayseri: ['Ankara', 'Konya', 'Adana', 'Gaziantep'],
    Eskisehir: ['Ankara', 'Istanbul', 'Bursa'],
    Trabzon: ['Erzurum'],
    Erzurum: ['Trabzon', 'Diyarbakir', 'Van'],
    Van: ['Diyarbakir', 'Erzurum'],
  },

  [Country.SAUDI_ARABIA]: {
    Riyadh: ['Dammam', 'Buraidah', 'Hail', 'Khobar'],
    Jeddah: ['Mecca', 'Medina', 'Taif'],
    Mecca: ['Jeddah', 'Taif', 'Khamis Mushait'],
    Medina: ['Jeddah', 'Tabuk', 'Hail'],
    Dammam: ['Riyadh', 'Khobar', 'Dhahran', 'Jubail'],
    Khobar: ['Riyadh', 'Dammam', 'Dhahran', 'Hofuf'],
    Dhahran: ['Dammam', 'Khobar', 'Hofuf'],
    Tabuk: ['Medina'],
    Buraidah: ['Riyadh', 'Hail'],
    'Khamis Mushait': ['Mecca', 'Najran'],
    Hofuf: ['Khobar', 'Dhahran'],
    Taif: ['Jeddah', 'Mecca'],
    Jubail: ['Dammam'],
    Hail: ['Riyadh', 'Medina', 'Buraidah'],
    Najran: ['Khamis Mushait'],
  },

  [Country.ARGENTINA]: {
    'Buenos Aires': ['Rosario', 'La Plata', 'Cordoba'],
    Cordoba: ['Buenos Aires', 'San Miguel de Tucuman', 'Santa Fe'],
    Rosario: ['Buenos Aires', 'Santa Fe'],
    Mendoza: ['San Juan', 'Neuquen'],
    'La Plata': ['Buenos Aires', 'Mar del Plata'],
    'San Miguel de Tucuman': ['Cordoba', 'Salta', 'Resistencia'],
    'Mar del Plata': ['La Plata'],
    Salta: ['San Miguel de Tucuman', 'San Juan'],
    'Santa Fe': ['Cordoba', 'Rosario', 'Resistencia'],
    'San Juan': ['Mendoza', 'Salta'],
    Neuquen: ['Mendoza', 'Bariloche'],
    Resistencia: ['San Miguel de Tucuman', 'Santa Fe'],
    Bariloche: ['Neuquen', 'Ushuaia', 'Comodoro Rivadavia'],
    Ushuaia: ['Bariloche', 'Comodoro Rivadavia'],
    'Comodoro Rivadavia': ['Bariloche', 'Ushuaia'],
  },

  [Country.POLAND]: {
    Warsaw: ['Lodz', 'Lublin', 'Radom', 'Bialystok'],
    Krakow: ['Katowice', 'Czestochowa', 'Wroclaw'],
    Lodz: ['Warsaw', 'Wroclaw', 'Poznan'],
    Wroclaw: ['Lodz', 'Krakow', 'Poznan'],
    Poznan: ['Lodz', 'Wroclaw', 'Bydgoszcz'],
    Gdansk: ['Gdynia', 'Bydgoszcz', 'Torun'],
    Szczecin: ['Bydgoszcz'],
    Bydgoszcz: ['Poznan', 'Gdansk', 'Szczecin', 'Torun'],
    Lublin: ['Warsaw', 'Radom'],
    Katowice: ['Krakow', 'Czestochowa'],
    Bialystok: ['Warsaw'],
    Gdynia: ['Gdansk'],
    Czestochowa: ['Krakow', 'Katowice'],
    Radom: ['Warsaw', 'Lublin'],
    Torun: ['Gdansk', 'Bydgoszcz'],
  },

  [Country.EGYPT]: {
    Cairo: ['Giza', 'Alexandria', 'Shubra El Kheima', 'Suez'],
    Alexandria: ['Cairo', 'Mansoura', 'Tanta'],
    Giza: ['Cairo'],
    'Shubra El Kheima': ['Cairo', 'Port Said', 'Ismailia'],
    'Port Said': ['Shubra El Kheima', 'Suez', 'Ismailia'],
    Suez: ['Cairo', 'Port Said', 'Ismailia'],
    Luxor: ['Aswan', 'Asyut', 'Hurghada'],
    Aswan: ['Luxor'],
    Mansoura: ['Alexandria', 'Tanta'],
    Tanta: ['Alexandria', 'Mansoura', 'Minya'],
    Asyut: ['Luxor', 'Minya'],
    Ismailia: ['Shubra El Kheima', 'Port Said', 'Suez'],
    Hurghada: ['Luxor', 'Sharm El Sheikh'],
    'Sharm El Sheikh': ['Hurghada'],
    Minya: ['Tanta', 'Asyut'],
  },

  [Country.INDONESIA]: {
    Jakarta: ['Tangerang', 'Bandung', 'Depok', 'Semarang'],
    Surabaya: ['Semarang', 'Yogyakarta'],
    Bandung: ['Jakarta', 'Depok'],
    Medan: ['Batam', 'Palembang', 'Padang'],
    Semarang: ['Jakarta', 'Surabaya', 'Yogyakarta'],
    Makassar: ['Denpasar', 'Balikpapan'],
    Palembang: ['Medan', 'Batam', 'Depok'],
    Tangerang: ['Jakarta'],
    Depok: ['Jakarta', 'Bandung', 'Palembang'],
    Batam: ['Medan', 'Palembang', 'Padang'],
    Padang: ['Medan', 'Batam'],
    Denpasar: ['Makassar', 'Yogyakarta'],
    Manado: ['Balikpapan'],
    Yogyakarta: ['Semarang', 'Surabaya', 'Denpasar'],
    Balikpapan: ['Makassar', 'Manado'],
  },

  [Country.SOUTH_AFRICA]: {
    Pretoria: ['Johannesburg', 'Soweto', 'Rustenburg', 'Polokwane'],
    'Cape Town': ['George', 'Port Elizabeth', 'Kimberley'],
    Johannesburg: ['Pretoria', 'Soweto', 'Bloemfontein'],
    Durban: ['Pietermaritzburg', 'Richards Bay', 'East London'],
    Soweto: ['Pretoria', 'Johannesburg', 'Rustenburg'],
    'Port Elizabeth': ['Cape Town', 'East London'],
    Pietermaritzburg: ['Durban', 'Bloemfontein'],
    'East London': ['Durban', 'Port Elizabeth'],
    Bloemfontein: ['Johannesburg', 'Pietermaritzburg', 'Kimberley'],
    Nelspruit: ['Polokwane', 'Richards Bay'],
    Kimberley: ['Cape Town', 'Bloemfontein'],
    Polokwane: ['Pretoria', 'Nelspruit'],
    George: ['Cape Town'],
    Rustenburg: ['Pretoria', 'Soweto'],
    'Richards Bay': ['Durban', 'Nelspruit'],
  },

  [Country.NIGERIA]: {
    Abuja: ['Kaduna', 'Jos', 'Ilorin', 'Kano'],
    Lagos: ['Ibadan', 'Aba'],
    Kano: ['Abuja', 'Kaduna', 'Zaria', 'Sokoto'],
    Ibadan: ['Lagos', 'Ilorin', 'Benin City'],
    Kaduna: ['Abuja', 'Kano', 'Zaria', 'Jos'],
    'Port Harcourt': ['Benin City', 'Aba', 'Enugu', 'Calabar'],
    'Benin City': ['Ibadan', 'Port Harcourt', 'Enugu'],
    Maiduguri: ['Zaria'],
    Zaria: ['Kano', 'Kaduna', 'Maiduguri'],
    Jos: ['Abuja', 'Kaduna'],
    Ilorin: ['Abuja', 'Ibadan'],
    Aba: ['Lagos', 'Port Harcourt', 'Enugu'],
    Enugu: ['Port Harcourt', 'Benin City', 'Aba', 'Calabar'],
    Sokoto: ['Kano'],
    Calabar: ['Port Harcourt', 'Enugu'],
  },

  [Country.DENMARK]: {
    Copenhagen: ['Roskilde', 'Helsingor', 'Odense'],
    Aarhus: ['Aalborg', 'Randers', 'Horsens'],
    Odense: ['Copenhagen', 'Kolding', 'Vejle'],
    Aalborg: ['Aarhus', 'Randers'],
    Esbjerg: ['Horsens', 'Herning'],
    Randers: ['Aarhus', 'Aalborg'],
    Kolding: ['Odense', 'Vejle'],
    Horsens: ['Aarhus', 'Esbjerg'],
    Vejle: ['Odense', 'Kolding', 'Herning'],
    Roskilde: ['Copenhagen'],
    Herning: ['Esbjerg', 'Vejle'],
    Helsingor: ['Copenhagen'],
  },

  [Country.ESTONIA]: {
    Tallinn: ['Maardu', 'Rakvere', 'Haapsalu'],
    Tartu: ['Viljandi', 'Valga'],
    Narva: ['Kohtla-Jarve', 'Sillamae'],
    Parnu: ['Viljandi', 'Kuressaare'],
    'Kohtla-Jarve': ['Narva', 'Sillamae', 'Rakvere'],
    Viljandi: ['Tartu', 'Parnu'],
    Rakvere: ['Tallinn', 'Kohtla-Jarve', 'Maardu'],
    Maardu: ['Tallinn', 'Rakvere'],
    Kuressaare: ['Parnu', 'Haapsalu'],
    Sillamae: ['Narva', 'Kohtla-Jarve'],
    Valga: ['Tartu'],
    Haapsalu: ['Tallinn', 'Kuressaare'],
  },

  [Country.UKRAINE]: {
    Kyiv: ['Chernihiv', 'Poltava', 'Vinnytsia'],
    Kharkiv: ['Poltava', 'Luhansk', 'Chernihiv'],
    Odesa: ['Vinnytsia', 'Mykolaiv', 'Simferopol'],
    Dnipro: ['Poltava', 'Zaporizhzhia', 'Kryvyi Rih'],
    Donetsk: ['Luhansk', 'Mariupol', 'Dnipro'],
    Zaporizhzhia: ['Dnipro', 'Kryvyi Rih', 'Mariupol'],
    Lviv: ['Vinnytsia'],
    'Kryvyi Rih': ['Dnipro', 'Zaporizhzhia', 'Mykolaiv'],
    Mykolaiv: ['Odesa', 'Kryvyi Rih', 'Simferopol'],
    Mariupol: ['Donetsk', 'Zaporizhzhia'],
    Luhansk: ['Kharkiv', 'Donetsk'],
    Vinnytsia: ['Kyiv', 'Odesa', 'Lviv'],
    Simferopol: ['Odesa', 'Mykolaiv'],
    Chernihiv: ['Kyiv', 'Kharkiv'],
    Poltava: ['Kyiv', 'Kharkiv', 'Dnipro'],
  },

  [Country.NETHERLANDS]: {
    Amsterdam: ['Utrecht', 'Haarlem', 'Almere'],
    Rotterdam: ['The Hague', 'Utrecht', 'Breda'],
    'The Hague': ['Rotterdam', 'Utrecht'],
    Utrecht: ['Amsterdam', 'Rotterdam', 'The Hague', 'Apeldoorn'],
    Eindhoven: ['Tilburg', 'Breda', 'Nijmegen', 'Maastricht'],
    Groningen: ['Apeldoorn', 'Enschede'],
    Tilburg: ['Eindhoven', 'Breda'],
    Almere: ['Amsterdam', 'Apeldoorn'],
    Breda: ['Rotterdam', 'Eindhoven', 'Tilburg'],
    Nijmegen: ['Eindhoven', 'Apeldoorn', 'Arnhem'],
    Apeldoorn: ['Utrecht', 'Almere', 'Groningen', 'Nijmegen', 'Arnhem'],
    Arnhem: ['Nijmegen', 'Apeldoorn', 'Enschede'],
    Haarlem: ['Amsterdam'],
    Enschede: ['Groningen', 'Arnhem'],
    Maastricht: ['Eindhoven'],
  },

  [Country.SWEDEN]: {
    Stockholm: ['Uppsala', 'Vasteras', 'Norrkoping'],
    Gothenburg: ['Boras', 'Orebro', 'Jonkoping'],
    Malmo: ['Lund', 'Helsingborg'],
    Uppsala: ['Stockholm', 'Gavle', 'Vasteras'],
    Vasteras: ['Stockholm', 'Uppsala', 'Orebro'],
    Orebro: ['Gothenburg', 'Vasteras', 'Linkoping'],
    Linkoping: ['Orebro', 'Norrkoping', 'Jonkoping'],
    Helsingborg: ['Malmo', 'Jonkoping'],
    Jonkoping: ['Gothenburg', 'Linkoping', 'Helsingborg', 'Boras'],
    Norrkoping: ['Stockholm', 'Linkoping'],
    Lund: ['Malmo', 'Boras'],
    Umea: ['Sundsvall'],
    Gavle: ['Uppsala', 'Sundsvall'],
    Boras: ['Gothenburg', 'Jonkoping', 'Lund'],
    Sundsvall: ['Umea', 'Gavle'],
  },

  [Country.ISRAEL]: {
    Jerusalem: ['Tel Aviv', 'Beer Sheva', 'Rishon LeZion'],
    'Tel Aviv': ['Jerusalem', 'Rishon LeZion', 'Petah Tikva', 'Holon'],
    Haifa: ['Netanya', 'Petah Tikva', 'Herzliya'],
    'Rishon LeZion': ['Jerusalem', 'Tel Aviv', 'Ashdod', 'Rehovot'],
    'Petah Tikva': ['Tel Aviv', 'Haifa', 'Bnei Brak', 'Herzliya'],
    Ashdod: ['Rishon LeZion', 'Ashkelon', 'Rehovot'],
    Netanya: ['Haifa', 'Herzliya'],
    'Beer Sheva': ['Jerusalem', 'Eilat', 'Rehovot'],
    Holon: ['Tel Aviv', 'Ramat Gan', 'Bnei Brak'],
    'Bnei Brak': ['Petah Tikva', 'Holon', 'Ramat Gan'],
    'Ramat Gan': ['Holon', 'Bnei Brak'],
    Ashkelon: ['Ashdod'],
    Rehovot: ['Rishon LeZion', 'Ashdod', 'Beer Sheva'],
    Herzliya: ['Haifa', 'Netanya', 'Petah Tikva'],
    Eilat: ['Beer Sheva'],
  },

  [Country.BELGIUM]: {
    Brussels: ['Antwerp', 'Leuven', 'Charleroi', 'Aalst'],
    Antwerp: ['Brussels', 'Mechelen', 'Ghent'],
    Ghent: ['Antwerp', 'Bruges', 'Aalst'],
    Charleroi: ['Brussels', 'Mons', 'Namur'],
    Liege: ['Leuven', 'Namur', 'Hasselt'],
    Bruges: ['Ghent', 'Mechelen'],
    Namur: ['Charleroi', 'Liege'],
    Leuven: ['Brussels', 'Liege', 'Mechelen', 'Hasselt'],
    Mons: ['Charleroi'],
    Mechelen: ['Antwerp', 'Bruges', 'Leuven'],
    Aalst: ['Brussels', 'Ghent'],
    Hasselt: ['Liege', 'Leuven'],
  },

  [Country.SWITZERLAND]: {
    Bern: ['Basel', 'Lucerne', 'Lausanne', 'Biel'],
    Zurich: ['Basel', 'Winterthur', 'St. Gallen', 'Lucerne'],
    Geneva: ['Lausanne', 'Thun'],
    Basel: ['Bern', 'Zurich', 'Winterthur'],
    Lausanne: ['Bern', 'Geneva', 'Thun'],
    Winterthur: ['Zurich', 'Basel', 'St. Gallen'],
    Lucerne: ['Bern', 'Zurich', 'Chur'],
    'St. Gallen': ['Zurich', 'Winterthur', 'Chur'],
    Lugano: ['Chur'],
    Biel: ['Bern'],
    Thun: ['Geneva', 'Lausanne'],
    Chur: ['Lucerne', 'St. Gallen', 'Lugano'],
  },

  [Country.AUSTRIA]: {
    Vienna: ['Linz', 'St. Polten', 'Graz', 'Wiener Neustadt'],
    Graz: ['Vienna', 'Klagenfurt', 'Villach'],
    Linz: ['Vienna', 'Salzburg', 'Wels'],
    Salzburg: ['Linz', 'Innsbruck', 'Wels'],
    Innsbruck: ['Salzburg', 'Dornbirn', 'Klagenfurt'],
    Klagenfurt: ['Graz', 'Innsbruck', 'Villach'],
    Villach: ['Graz', 'Klagenfurt'],
    Wels: ['Linz', 'Salzburg', 'Steyr'],
    'St. Polten': ['Vienna', 'Wiener Neustadt'],
    Dornbirn: ['Innsbruck'],
    'Wiener Neustadt': ['Vienna', 'St. Polten'],
    Steyr: ['Wels'],
  },

  [Country.NORWAY]: {
    Oslo: ['Bergen', 'Trondheim', 'Drammen', 'Asker'],
    Bergen: ['Oslo', 'Stavanger', 'Sandnes'],
    Trondheim: ['Oslo', 'Tromso'],
    Stavanger: ['Bergen', 'Sandnes', 'Kristiansand'],
    Drammen: ['Oslo', 'Asker', 'Skien'],
    Fredrikstad: ['Oslo', 'Sarpsborg'],
    Kristiansand: ['Stavanger', 'Skien'],
    Tromso: ['Trondheim'],
    Sandnes: ['Bergen', 'Stavanger'],
    Asker: ['Oslo', 'Drammen'],
    Sarpsborg: ['Fredrikstad'],
    Skien: ['Drammen', 'Kristiansand'],
  },

  [Country.FINLAND]: {
    Helsinki: ['Espoo', 'Vantaa', 'Lahti', 'Turku'],
    Espoo: ['Helsinki', 'Vantaa'],
    Tampere: ['Jyvaskyla', 'Pori', 'Turku'],
    Vantaa: ['Helsinki', 'Espoo', 'Lahti'],
    Oulu: ['Kuopio'],
    Turku: ['Helsinki', 'Tampere', 'Pori'],
    Jyvaskyla: ['Tampere', 'Kuopio', 'Joensuu'],
    Lahti: ['Helsinki', 'Vantaa', 'Lappeenranta'],
    Kuopio: ['Oulu', 'Jyvaskyla', 'Joensuu'],
    Pori: ['Tampere', 'Turku'],
    Joensuu: ['Jyvaskyla', 'Kuopio', 'Lappeenranta'],
    Lappeenranta: ['Lahti', 'Joensuu'],
  },

  [Country.GREECE]: {
    Athens: ['Thessaloniki', 'Patras', 'Heraklion', 'Chalcis'],
    Thessaloniki: ['Athens', 'Larissa', 'Katerini'],
    Patras: ['Athens', 'Agrinio'],
    Heraklion: ['Athens', 'Chania'],
    Larissa: ['Thessaloniki', 'Volos', 'Katerini'],
    Volos: ['Larissa', 'Chalcis'],
    Rhodes: [],
    Ioannina: ['Agrinio'],
    Chania: ['Heraklion'],
    Chalcis: ['Athens', 'Volos'],
    Agrinio: ['Patras', 'Ioannina'],
    Katerini: ['Thessaloniki', 'Larissa'],
  },

  [Country.PORTUGAL]: {
    Lisbon: ['Amadora', 'Porto', 'Setubal', 'Agualva-Cacem'],
    Porto: ['Lisbon', 'Vila Nova de Gaia', 'Braga'],
    'Vila Nova de Gaia': ['Porto', 'Braga'],
    Amadora: ['Lisbon', 'Agualva-Cacem'],
    Braga: ['Porto', 'Vila Nova de Gaia', 'Coimbra'],
    Coimbra: ['Braga', 'Aveiro'],
    Funchal: [],
    Setubal: ['Lisbon', 'Almada'],
    Almada: ['Setubal', 'Faro'],
    'Agualva-Cacem': ['Lisbon', 'Amadora'],
    Faro: ['Almada'],
    Aveiro: ['Coimbra'],
  },

  [Country.RUSSIA]: {
    Moscow: ['Nizhny Novgorod', 'Kazan', 'Yekaterinburg'],
    'St Petersburg': ['Kaliningrad', 'Murmansk', 'Nizhny Novgorod'],
    Novosibirsk: ['Omsk', 'Krasnoyarsk', 'Yekaterinburg'],
    Yekaterinburg: ['Moscow', 'Novosibirsk', 'Chelyabinsk'],
    Vladivostok: ['Khabarovsk'],
    'Nizhny Novgorod': ['Moscow', 'Samara', 'Kazan', 'St Petersburg'],
    Volgograd: ['Rostov-on-Don', 'Samara', 'Sochi'],
    'Rostov-on-Don': ['Volgograd', 'Sochi'],
    Kazan: ['Moscow', 'Nizhny Novgorod', 'Ufa', 'Perm'],
    Omsk: ['Novosibirsk', 'Chelyabinsk'],
    Samara: ['Nizhny Novgorod', 'Volgograd', 'Ufa'],
    Chelyabinsk: ['Yekaterinburg', 'Omsk', 'Ufa'],
    Kaliningrad: ['St Petersburg'],
    Krasnoyarsk: ['Novosibirsk', 'Irkutsk'],
    Irkutsk: ['Krasnoyarsk', 'Khabarovsk'],
    Khabarovsk: ['Vladivostok', 'Irkutsk'],
    Murmansk: ['St Petersburg', 'Perm'],
    Sochi: ['Rostov-on-Don', 'Volgograd'],
    Perm: ['Kazan', 'Murmansk', 'Ufa'],
    Ufa: ['Kazan', 'Perm', 'Chelyabinsk', 'Samara'],
  },

  [Country.INDIA]: {
    'New Delhi': ['Jaipur', 'Lucknow', 'Ahmedabad', 'Kanpur'],
    Mumbai: ['Ahmedabad', 'Pune', 'Surat'],
    Bangalore: ['Hyderabad', 'Chennai', 'Kochi'],
    Kolkata: ['Patna', 'Varanasi', 'Guwahati'],
    Chennai: ['Bangalore', 'Hyderabad', 'Visakhapatnam'],
    Hyderabad: ['Bangalore', 'Chennai', 'Nagpur', 'Visakhapatnam'],
    Ahmedabad: ['New Delhi', 'Mumbai', 'Surat', 'Bhopal'],
    Pune: ['Mumbai', 'Nagpur', 'Kochi'],
    Surat: ['Mumbai', 'Ahmedabad'],
    Jaipur: ['New Delhi', 'Amritsar', 'Bhopal'],
    Lucknow: ['New Delhi', 'Kanpur', 'Varanasi', 'Patna'],
    Kanpur: ['New Delhi', 'Lucknow', 'Patna'],
    Nagpur: ['Hyderabad', 'Pune', 'Bhopal'],
    Patna: ['Kolkata', 'Lucknow', 'Kanpur', 'Varanasi', 'Guwahati'],
    Bhopal: ['Ahmedabad', 'Nagpur', 'Jaipur'],
    Kochi: ['Bangalore', 'Pune'],
    Varanasi: ['Kolkata', 'Lucknow', 'Patna'],
    Amritsar: ['Jaipur'],
    Guwahati: ['Kolkata', 'Patna'],
    Visakhapatnam: ['Chennai', 'Hyderabad'],
  },

  [Country.BRAZIL]: {
    Brasilia: ['Goiania', 'Belo Horizonte', 'Salvador', 'Belem'],
    'Sao Paulo': ['Rio de Janeiro', 'Belo Horizonte', 'Campinas', 'Guarulhos'],
    'Rio de Janeiro': ['Sao Paulo', 'Belo Horizonte'],
    Salvador: ['Brasilia', 'Natal'],
    Fortaleza: ['Recife', 'Natal', 'Belem'],
    'Belo Horizonte': ['Brasilia', 'Sao Paulo', 'Rio de Janeiro', 'Campinas'],
    Manaus: ['Belem'],
    Curitiba: ['Porto Alegre', 'Campinas', 'Guarulhos'],
    Recife: ['Fortaleza', 'Natal'],
    'Porto Alegre': ['Curitiba', 'Goiania'],
    Belem: ['Brasilia', 'Fortaleza', 'Manaus'],
    Goiania: ['Brasilia', 'Porto Alegre', 'Campinas'],
    Guarulhos: ['Sao Paulo', 'Curitiba'],
    Campinas: ['Sao Paulo', 'Belo Horizonte', 'Goiania', 'Curitiba'],
    Natal: ['Salvador', 'Fortaleza', 'Recife'],
  },

  [Country.CANADA]: {
    Ottawa: ['Montreal', 'Toronto', 'Quebec City', 'Hamilton', 'Winnipeg'],
    Toronto: ['Ottawa', 'Hamilton', 'Montreal'],
    Montreal: ['Ottawa', 'Toronto', 'Quebec City', 'Halifax'],
    Vancouver: ['Victoria', 'Calgary'],
    Calgary: ['Vancouver', 'Edmonton', 'Regina', 'Saskatoon'],
    Edmonton: ['Calgary', 'Saskatoon', 'Yellowknife'],
    'Quebec City': ['Montreal', 'Ottawa'],
    Winnipeg: ['Regina', 'Saskatoon', 'Ottawa'],
    Hamilton: ['Toronto', 'Ottawa'],
    Halifax: ['Montreal', 'St Johns'],
    Victoria: ['Vancouver'],
    Regina: ['Calgary', 'Winnipeg', 'Saskatoon'],
    Saskatoon: ['Calgary', 'Edmonton', 'Regina', 'Winnipeg', 'Yellowknife'],
    'St Johns': ['Halifax'],
    Yellowknife: ['Edmonton', 'Saskatoon'],
  },

  [Country.AUSTRALIA]: {
    Canberra: ['Sydney', 'Melbourne', 'Wollongong'],
    Sydney: ['Canberra', 'Newcastle', 'Brisbane', 'Wollongong'],
    Melbourne: ['Canberra', 'Adelaide', 'Geelong', 'Hobart'],
    Brisbane: ['Sydney', 'Gold Coast', 'Newcastle', 'Townsville'],
    Perth: ['Adelaide'],
    Adelaide: ['Perth', 'Melbourne', 'Alice Springs'],
    'Gold Coast': ['Brisbane', 'Newcastle'],
    Newcastle: ['Sydney', 'Brisbane', 'Gold Coast'],
    Darwin: ['Cairns', 'Alice Springs'],
    Hobart: ['Melbourne', 'Geelong'],
    Cairns: ['Darwin', 'Townsville'],
    Townsville: ['Brisbane', 'Cairns'],
    'Alice Springs': ['Adelaide', 'Darwin'],
    Geelong: ['Melbourne', 'Hobart'],
    Wollongong: ['Sydney', 'Canberra'],
  },

  [Country.ITALY]: {
    Rome: ['Florence', 'Naples', 'Bologna'],
    Milan: ['Turin', 'Genoa', 'Verona', 'Bologna'],
    Naples: ['Rome', 'Bari', 'Palermo'],
    Turin: ['Milan', 'Genoa'],
    Palermo: ['Naples', 'Catania', 'Cagliari'],
    Genoa: ['Milan', 'Turin', 'Bologna'],
    Bologna: ['Milan', 'Genoa', 'Florence', 'Rome', 'Venice'],
    Florence: ['Bologna', 'Rome'],
    Venice: ['Bologna', 'Verona', 'Trieste'],
    Bari: ['Naples', 'Messina'],
    Catania: ['Palermo', 'Messina'],
    Verona: ['Milan', 'Venice'],
    Messina: ['Catania', 'Bari'],
    Trieste: ['Venice'],
    Cagliari: ['Palermo'],
  },

  [Country.SPAIN]: {
    Madrid: ['Toledo', 'Valladolid', 'Zaragoza', 'Valencia'],
    Barcelona: ['Valencia', 'Zaragoza', 'Palma'],
    Valencia: ['Madrid', 'Barcelona', 'Murcia', 'Toledo'],
    Seville: ['Cordoba', 'Granada', 'Malaga', 'Las Palmas'],
    Zaragoza: ['Madrid', 'Barcelona', 'Bilbao', 'Valladolid'],
    Malaga: ['Seville', 'Granada'],
    Bilbao: ['Zaragoza', 'Valladolid', 'Vigo'],
    Murcia: ['Valencia', 'Granada'],
    Palma: ['Barcelona'],
    'Las Palmas': ['Seville'],
    Valladolid: ['Madrid', 'Zaragoza', 'Bilbao', 'Vigo'],
    Cordoba: ['Seville', 'Granada', 'Toledo'],
    Vigo: ['Bilbao', 'Valladolid'],
    Granada: ['Seville', 'Cordoba', 'Malaga', 'Murcia'],
    Toledo: ['Madrid', 'Valencia', 'Cordoba'],
  },

  [Country.SOUTH_KOREA]: {
    Seoul: ['Incheon', 'Suwon', 'Seongnam', 'Daejeon', 'Goyang'],
    Busan: ['Daegu', 'Ulsan', 'Changwon'],
    Incheon: ['Seoul', 'Goyang'],
    Daegu: ['Busan', 'Yongin', 'Daejeon', 'Jeonju'],
    Daejeon: ['Seoul', 'Daegu', 'Jeonju', 'Suwon'],
    Gwangju: ['Jeonju', 'Jeju'],
    Suwon: ['Seoul', 'Daejeon', 'Yongin'],
    Ulsan: ['Busan', 'Changwon'],
    Changwon: ['Busan', 'Ulsan', 'Jeju'],
    Goyang: ['Seoul', 'Incheon', 'Pyongyang'],
    Yongin: ['Suwon', 'Daegu', 'Seongnam'],
    Seongnam: ['Seoul', 'Yongin'],
    Jeju: ['Gwangju', 'Changwon'],
    Jeonju: ['Daejeon', 'Daegu', 'Gwangju'],
    Pyongyang: ['Goyang'],
  },

  [Country.MEXICO]: {
    'Mexico City': ['Puebla', 'Toluca', 'Queretaro', 'Veracruz'],
    Guadalajara: ['Zapopan', 'Leon', 'Toluca'],
    Monterrey: ['Juarez', 'Queretaro', 'Hermosillo'],
    Puebla: ['Mexico City', 'Veracruz'],
    Tijuana: ['Hermosillo', 'Juarez'],
    Leon: ['Guadalajara', 'Queretaro', 'Zapopan'],
    Juarez: ['Tijuana', 'Monterrey', 'Hermosillo'],
    Zapopan: ['Guadalajara', 'Leon'],
    Cancun: ['Merida'],
    Merida: ['Cancun', 'Veracruz'],
    Queretaro: ['Mexico City', 'Monterrey', 'Leon', 'Toluca'],
    Veracruz: ['Mexico City', 'Puebla', 'Merida'],
    Acapulco: ['Toluca'],
    Toluca: ['Mexico City', 'Guadalajara', 'Queretaro', 'Acapulco'],
    Hermosillo: ['Tijuana', 'Juarez', 'Monterrey'],
  },

  [Country.TURKEY]: {
    Ankara: ['Istanbul', 'Eskisehir', 'Kayseri', 'Konya'],
    Istanbul: ['Ankara', 'Bursa', 'Eskisehir'],
    Izmir: ['Bursa', 'Antalya', 'Konya'],
    Bursa: ['Istanbul', 'Izmir', 'Eskisehir'],
    Antalya: ['Izmir', 'Konya', 'Mersin'],
    Adana: ['Mersin', 'Gaziantep', 'Kayseri'],
    Konya: ['Ankara', 'Izmir', 'Antalya', 'Mersin', 'Kayseri'],
    Gaziantep: ['Adana', 'Diyarbakir'],
    Mersin: ['Antalya', 'Konya', 'Adana'],
    Diyarbakir: ['Gaziantep', 'Van', 'Erzurum'],
    Kayseri: ['Ankara', 'Konya', 'Adana'],
    Eskisehir: ['Istanbul', 'Ankara', 'Bursa'],
    Trabzon: ['Erzurum'],
    Erzurum: ['Trabzon', 'Diyarbakir', 'Van'],
    Van: ['Diyarbakir', 'Erzurum'],
  },

  [Country.SAUDI_ARABIA]: {
    Riyadh: ['Buraidah', 'Hofuf', 'Taif', 'Hail'],
    Jeddah: ['Mecca', 'Taif'],
    Mecca: ['Jeddah', 'Taif'],
    Medina: ['Tabuk', 'Hail', 'Buraidah'],
    Dammam: ['Khobar', 'Hofuf', 'Jubail'],
    Khobar: ['Dammam', 'Dhahran'],
    Dhahran: ['Khobar', 'Hofuf'],
    Tabuk: ['Medina'],
    Buraidah: ['Medina', 'Riyadh', 'Hail'],
    'Khamis Mushait': ['Najran', 'Taif'],
    Hofuf: ['Riyadh', 'Dammam', 'Dhahran'],
    Taif: ['Riyadh', 'Jeddah', 'Mecca', 'Khamis Mushait'],
    Jubail: ['Dammam'],
    Hail: ['Medina', 'Buraidah', 'Riyadh'],
    Najran: ['Khamis Mushait'],
  },

  [Country.ARGENTINA]: {
    'Buenos Aires': ['La Plata', 'Rosario', 'Santa Fe'],
    Cordoba: ['San Miguel de Tucuman', 'Santa Fe', 'Rosario'],
    Rosario: ['Buenos Aires', 'Cordoba', 'Santa Fe'],
    Mendoza: ['San Juan', 'Neuquen'],
    'La Plata': ['Buenos Aires', 'Mar del Plata'],
    'San Miguel de Tucuman': ['Cordoba', 'Salta', 'Resistencia'],
    'Mar del Plata': ['La Plata'],
    Salta: ['San Miguel de Tucuman', 'San Juan'],
    'Santa Fe': ['Buenos Aires', 'Rosario', 'Cordoba', 'Resistencia'],
    'San Juan': ['Salta', 'Mendoza'],
    Neuquen: ['Mendoza', 'Bariloche', 'Comodoro Rivadavia'],
    Resistencia: ['San Miguel de Tucuman', 'Santa Fe'],
    Bariloche: ['Neuquen', 'Ushuaia'],
    Ushuaia: ['Bariloche', 'Comodoro Rivadavia'],
    'Comodoro Rivadavia': ['Neuquen', 'Ushuaia'],
  },

  [Country.POLAND]: {
    Warsaw: ['Lodz', 'Lublin', 'Radom', 'Torun'],
    Krakow: ['Katowice', 'Czestochowa'],
    Lodz: ['Warsaw', 'Wroclaw', 'Czestochowa', 'Torun'],
    Wroclaw: ['Lodz', 'Poznan', 'Czestochowa'],
    Poznan: ['Wroclaw', 'Bydgoszcz', 'Szczecin'],
    Gdansk: ['Gdynia', 'Bydgoszcz', 'Torun'],
    Szczecin: ['Poznan', 'Bydgoszcz'],
    Bydgoszcz: ['Poznan', 'Szczecin', 'Gdansk', 'Torun'],
    Lublin: ['Warsaw', 'Radom', 'Bialystok'],
    Katowice: ['Krakow', 'Czestochowa'],
    Bialystok: ['Lublin'],
    Gdynia: ['Gdansk'],
    Czestochowa: ['Krakow', 'Katowice', 'Lodz', 'Wroclaw'],
    Radom: ['Warsaw', 'Lublin'],
    Torun: ['Warsaw', 'Lodz', 'Gdansk', 'Bydgoszcz'],
  },

  [Country.EGYPT]: {
    Cairo: ['Giza', 'Alexandria', 'Shubra El Kheima', 'Suez', 'Asyut'],
    Alexandria: ['Cairo', 'Mansoura', 'Tanta'],
    Giza: ['Cairo', 'Minya'],
    'Shubra El Kheima': ['Cairo', 'Port Said', 'Ismailia'],
    'Port Said': ['Shubra El Kheima', 'Ismailia'],
    Suez: ['Cairo', 'Ismailia', 'Hurghada'],
    Luxor: ['Asyut', 'Aswan', 'Hurghada'],
    Aswan: ['Luxor'],
    Mansoura: ['Alexandria', 'Tanta'],
    Tanta: ['Alexandria', 'Mansoura'],
    Asyut: ['Cairo', 'Minya', 'Luxor'],
    Ismailia: ['Shubra El Kheima', 'Port Said', 'Suez'],
    Hurghada: ['Suez', 'Luxor', 'Sharm El Sheikh'],
    'Sharm El Sheikh': ['Hurghada'],
    Minya: ['Giza', 'Asyut'],
  },

  [Country.INDONESIA]: {
    Jakarta: ['Tangerang', 'Bandung', 'Depok'],
    Surabaya: ['Semarang', 'Yogyakarta', 'Denpasar'],
    Bandung: ['Jakarta', 'Yogyakarta', 'Semarang'],
    Medan: ['Batam', 'Padang'],
    Semarang: ['Bandung', 'Surabaya', 'Depok', 'Yogyakarta'],
    Makassar: ['Denpasar', 'Balikpapan'],
    Palembang: ['Padang', 'Batam', 'Depok'],
    Tangerang: ['Jakarta', 'Padang'],
    Depok: ['Jakarta', 'Semarang', 'Palembang'],
    Batam: ['Medan', 'Palembang'],
    Padang: ['Medan', 'Tangerang', 'Palembang'],
    Denpasar: ['Surabaya', 'Makassar'],
    Manado: ['Balikpapan'],
    Yogyakarta: ['Bandung', 'Semarang', 'Surabaya'],
    Balikpapan: ['Makassar', 'Manado'],
  },

  [Country.SOUTH_AFRICA]: {
    Pretoria: ['Johannesburg', 'Rustenburg', 'Nelspruit'],
    'Cape Town': ['George', 'Port Elizabeth'],
    Johannesburg: ['Pretoria', 'Soweto', 'Bloemfontein'],
    Durban: ['Pietermaritzburg', 'Richards Bay'],
    Soweto: ['Johannesburg', 'Bloemfontein'],
    'Port Elizabeth': ['Cape Town', 'George', 'East London'],
    Pietermaritzburg: ['Durban', 'Bloemfontein'],
    'East London': ['Port Elizabeth', 'Bloemfontein'],
    Bloemfontein: ['Johannesburg', 'Soweto', 'Pietermaritzburg', 'East London', 'Kimberley'],
    Nelspruit: ['Pretoria', 'Richards Bay', 'Polokwane'],
    Kimberley: ['Bloemfontein', 'George'],
    Polokwane: ['Nelspruit'],
    George: ['Cape Town', 'Port Elizabeth', 'Kimberley'],
    Rustenburg: ['Pretoria'],
    'Richards Bay': ['Durban', 'Nelspruit'],
  },

  [Country.NIGERIA]: {
    Abuja: ['Kaduna', 'Jos', 'Ilorin'],
    Lagos: ['Ibadan', 'Benin City', 'Aba'],
    Kano: ['Kaduna', 'Sokoto', 'Zaria'],
    Ibadan: ['Lagos', 'Ilorin', 'Benin City'],
    Kaduna: ['Abuja', 'Kano', 'Zaria'],
    'Port Harcourt': ['Aba', 'Calabar', 'Enugu'],
    'Benin City': ['Lagos', 'Ibadan', 'Enugu'],
    Maiduguri: ['Jos', 'Zaria'],
    Zaria: ['Kano', 'Kaduna', 'Maiduguri'],
    Jos: ['Abuja', 'Maiduguri'],
    Ilorin: ['Abuja', 'Ibadan'],
    Aba: ['Lagos', 'Port Harcourt'],
    Enugu: ['Benin City', 'Port Harcourt'],
    Sokoto: ['Kano'],
    Calabar: ['Port Harcourt'],
  },

  [Country.DENMARK]: {
    Copenhagen: ['Roskilde', 'Helsingor', 'Aarhus'],
    Aarhus: ['Copenhagen', 'Randers', 'Horsens', 'Aalborg'],
    Odense: ['Kolding', 'Roskilde', 'Vejle'],
    Aalborg: ['Aarhus', 'Randers'],
    Esbjerg: ['Vejle', 'Herning'],
    Randers: ['Aalborg', 'Aarhus', 'Herning'],
    Kolding: ['Odense', 'Vejle', 'Horsens'],
    Horsens: ['Aarhus', 'Kolding', 'Herning'],
    Vejle: ['Esbjerg', 'Kolding', 'Odense'],
    Roskilde: ['Copenhagen', 'Odense'],
    Herning: ['Esbjerg', 'Randers', 'Horsens'],
    Helsingor: ['Copenhagen'],
  },

  [Country.ESTONIA]: {
    Tallinn: ['Maardu', 'Rakvere', 'Haapsalu'],
    Tartu: ['Viljandi', 'Valga', 'Rakvere'],
    Narva: ['Kohtla-Jarve', 'Sillamae'],
    Parnu: ['Viljandi', 'Kuressaare', 'Haapsalu'],
    'Kohtla-Jarve': ['Narva', 'Rakvere'],
    Viljandi: ['Parnu', 'Tartu'],
    Rakvere: ['Tallinn', 'Kohtla-Jarve', 'Tartu'],
    Maardu: ['Tallinn'],
    Kuressaare: ['Parnu'],
    Sillamae: ['Narva'],
    Valga: ['Tartu'],
    Haapsalu: ['Tallinn', 'Parnu'],
  },

  [Country.UKRAINE]: {
    Kyiv: ['Chernihiv', 'Vinnytsia', 'Poltava'],
    Kharkiv: ['Poltava', 'Luhansk'],
    Odesa: ['Mykolaiv', 'Simferopol'],
    Dnipro: ['Poltava', 'Zaporizhzhia', 'Kryvyi Rih', 'Donetsk'],
    Donetsk: ['Dnipro', 'Luhansk', 'Mariupol'],
    Zaporizhzhia: ['Dnipro', 'Mariupol', 'Kryvyi Rih'],
    Lviv: ['Vinnytsia'],
    'Kryvyi Rih': ['Dnipro', 'Zaporizhzhia', 'Mykolaiv'],
    Mykolaiv: ['Odesa', 'Kryvyi Rih'],
    Mariupol: ['Donetsk', 'Zaporizhzhia'],
    Luhansk: ['Kharkiv', 'Donetsk'],
    Vinnytsia: ['Kyiv', 'Lviv'],
    Simferopol: ['Odesa'],
    Chernihiv: ['Kyiv'],
    Poltava: ['Kyiv', 'Kharkiv', 'Dnipro'],
  },

  [Country.NETHERLANDS]: {
    Amsterdam: ['Haarlem', 'Almere', 'Utrecht'],
    Rotterdam: ['The Hague', 'Breda', 'Tilburg'],
    'The Hague': ['Rotterdam', 'Utrecht', 'Haarlem'],
    Utrecht: ['Amsterdam', 'The Hague', 'Nijmegen', 'Apeldoorn'],
    Eindhoven: ['Tilburg', 'Breda', 'Maastricht'],
    Groningen: ['Apeldoorn', 'Enschede'],
    Tilburg: ['Rotterdam', 'Eindhoven', 'Breda'],
    Almere: ['Amsterdam', 'Apeldoorn'],
    Breda: ['Rotterdam', 'Tilburg', 'Eindhoven'],
    Nijmegen: ['Utrecht', 'Arnhem'],
    Apeldoorn: ['Utrecht', 'Almere', 'Groningen', 'Arnhem'],
    Arnhem: ['Nijmegen', 'Apeldoorn', 'Enschede'],
    Haarlem: ['Amsterdam', 'The Hague'],
    Enschede: ['Groningen', 'Arnhem'],
    Maastricht: ['Eindhoven'],
  },

  [Country.SWEDEN]: {
    Stockholm: ['Uppsala', 'Gavle', 'Vasteras', 'Norrkoping'],
    Gothenburg: ['Boras', 'Jonkoping', 'Orebro'],
    Malmo: ['Lund', 'Helsingborg'],
    Uppsala: ['Stockholm', 'Gavle'],
    Vasteras: ['Stockholm', 'Orebro'],
    Orebro: ['Gothenburg', 'Vasteras', 'Linkoping'],
    Linkoping: ['Orebro', 'Norrkoping', 'Jonkoping'],
    Helsingborg: ['Malmo', 'Jonkoping'],
    Jonkoping: ['Gothenburg', 'Helsingborg', 'Linkoping', 'Boras'],
    Norrkoping: ['Stockholm', 'Linkoping'],
    Lund: ['Malmo'],
    Umea: ['Sundsvall'],
    Gavle: ['Stockholm', 'Uppsala', 'Sundsvall'],
    Boras: ['Gothenburg', 'Jonkoping'],
    Sundsvall: ['Umea', 'Gavle'],
  },

  [Country.ISRAEL]: {
    Jerusalem: ['Tel Aviv', 'Rishon LeZion', 'Beer Sheva'],
    'Tel Aviv': ['Jerusalem', 'Holon', 'Ramat Gan', 'Petah Tikva', 'Rishon LeZion'],
    Haifa: ['Netanya', 'Herzliya', 'Bnei Brak'],
    'Rishon LeZion': ['Tel Aviv', 'Jerusalem', 'Ashdod'],
    'Petah Tikva': ['Tel Aviv', 'Netanya', 'Bnei Brak'],
    Ashdod: ['Rishon LeZion', 'Ashkelon', 'Rehovot'],
    Netanya: ['Haifa', 'Petah Tikva', 'Herzliya'],
    'Beer Sheva': ['Jerusalem', 'Rehovot', 'Eilat'],
    Holon: ['Tel Aviv', 'Ramat Gan'],
    'Bnei Brak': ['Haifa', 'Petah Tikva'],
    'Ramat Gan': ['Tel Aviv', 'Holon'],
    Ashkelon: ['Ashdod'],
    Rehovot: ['Ashdod', 'Beer Sheva'],
    Herzliya: ['Haifa', 'Netanya'],
    Eilat: ['Beer Sheva'],
  },

  [Country.BELGIUM]: {
    Brussels: ['Leuven', 'Aalst', 'Mechelen', 'Liege'],
    Antwerp: ['Mechelen', 'Hasselt'],
    Ghent: ['Bruges', 'Aalst'],
    Charleroi: ['Mons', 'Namur'],
    Liege: ['Brussels', 'Namur', 'Hasselt'],
    Bruges: ['Ghent'],
    Namur: ['Liege', 'Charleroi'],
    Leuven: ['Brussels', 'Mechelen'],
    Mons: ['Charleroi', 'Aalst'],
    Mechelen: ['Brussels', 'Antwerp', 'Leuven'],
    Aalst: ['Brussels', 'Ghent', 'Mons'],
    Hasselt: ['Antwerp', 'Liege'],
  },

  [Country.SWITZERLAND]: {
    Bern: ['Biel', 'Thun', 'Lucerne'],
    Zurich: ['Winterthur', 'St. Gallen', 'Lucerne'],
    Geneva: ['Lausanne'],
    Basel: ['Lucerne', 'Winterthur'],
    Lausanne: ['Geneva', 'Thun', 'Biel'],
    Winterthur: ['Zurich', 'Basel'],
    Lucerne: ['Bern', 'Zurich', 'Basel', 'Chur'],
    'St. Gallen': ['Zurich', 'Chur'],
    Lugano: ['Chur'],
    Biel: ['Bern', 'Lausanne'],
    Thun: ['Bern', 'Lausanne'],
    Chur: ['St. Gallen', 'Lucerne', 'Lugano'],
  },

  [Country.AUSTRIA]: {
    Vienna: ['St. Polten', 'Wiener Neustadt', 'Linz'],
    Graz: ['Wiener Neustadt', 'Steyr', 'Klagenfurt'],
    Linz: ['Vienna', 'Wels', 'Steyr'],
    Salzburg: ['Wels', 'Innsbruck'],
    Innsbruck: ['Salzburg', 'Dornbirn'],
    Klagenfurt: ['Graz', 'Villach'],
    Villach: ['Klagenfurt'],
    Wels: ['Linz', 'Salzburg', 'Steyr'],
    'St. Polten': ['Vienna', 'Steyr'],
    Dornbirn: ['Innsbruck'],
    'Wiener Neustadt': ['Vienna', 'Graz'],
    Steyr: ['Linz', 'Wels', 'St. Polten', 'Graz'],
  },

  [Country.NORWAY]: {
    Oslo: ['Drammen', 'Asker', 'Fredrikstad'],
    Bergen: ['Sandnes', 'Stavanger'],
    Trondheim: ['Drammen'],
    Stavanger: ['Bergen', 'Sandnes', 'Kristiansand'],
    Drammen: ['Oslo', 'Trondheim', 'Asker', 'Skien'],
    Fredrikstad: ['Oslo', 'Sarpsborg', 'Tromso'],
    Kristiansand: ['Stavanger', 'Skien'],
    Tromso: ['Fredrikstad'],
    Sandnes: ['Bergen', 'Stavanger'],
    Asker: ['Oslo', 'Drammen'],
    Sarpsborg: ['Fredrikstad'],
    Skien: ['Drammen', 'Kristiansand'],
  },

  [Country.FINLAND]: {
    Helsinki: ['Espoo', 'Vantaa', 'Lahti'],
    Espoo: ['Helsinki', 'Turku'],
    Tampere: ['Pori', 'Turku', 'Jyvaskyla'],
    Vantaa: ['Helsinki', 'Lahti'],
    Oulu: ['Kuopio'],
    Turku: ['Espoo', 'Tampere', 'Pori'],
    Jyvaskyla: ['Tampere', 'Kuopio', 'Lahti'],
    Lahti: ['Helsinki', 'Vantaa', 'Jyvaskyla', 'Lappeenranta'],
    Kuopio: ['Oulu', 'Jyvaskyla', 'Joensuu'],
    Pori: ['Turku', 'Tampere'],
    Joensuu: ['Kuopio', 'Lappeenranta'],
    Lappeenranta: ['Lahti', 'Joensuu'],
  },

  [Country.GREECE]: {
    Athens: ['Chalcis', 'Patras', 'Heraklion'],
    Thessaloniki: ['Katerini', 'Larissa'],
    Patras: ['Athens', 'Agrinio'],
    Heraklion: ['Athens', 'Chania', 'Rhodes'],
    Larissa: ['Thessaloniki', 'Katerini', 'Volos', 'Ioannina'],
    Volos: ['Larissa', 'Chalcis'],
    Rhodes: ['Heraklion'],
    Ioannina: ['Larissa', 'Agrinio'],
    Chania: ['Heraklion'],
    Chalcis: ['Athens', 'Volos'],
    Agrinio: ['Patras', 'Ioannina'],
    Katerini: ['Thessaloniki', 'Larissa'],
  },

  [Country.PORTUGAL]: {
    Lisbon: ['Amadora', 'Agualva-Cacem', 'Setubal', 'Almada'],
    Porto: ['Vila Nova de Gaia', 'Braga', 'Coimbra'],
    'Vila Nova de Gaia': ['Porto', 'Aveiro'],
    Amadora: ['Lisbon', 'Agualva-Cacem'],
    Braga: ['Porto'],
    Coimbra: ['Porto', 'Aveiro', 'Agualva-Cacem'],
    Funchal: ['Setubal'],
    Setubal: ['Lisbon', 'Funchal', 'Almada'],
    Almada: ['Lisbon', 'Setubal', 'Faro'],
    'Agualva-Cacem': ['Lisbon', 'Amadora', 'Coimbra'],
    Faro: ['Almada'],
    Aveiro: ['Vila Nova de Gaia', 'Coimbra'],
  },

  // Add more countries as needed...
}

// Helper function to validate city neighbors
export function validateCityNeighbors(neighbors: CityNeighbors): {
  valid: boolean
  errors: string[]
} {
  const errors: string[] = []

  // Check if each city has at least 2 neighbors (except for edge cases)
  for (const [city, cityNeighbors] of Object.entries(neighbors)) {
    if (cityNeighbors.length < 1) {
      errors.push(`${city} has no neighbors`)
    }

    // Check bidirectional connections
    for (const neighbor of cityNeighbors) {
      if (!neighbors[neighbor]) {
        errors.push(`${neighbor} (neighbor of ${city}) is not defined`)
      } else if (!neighbors[neighbor].includes(city)) {
        errors.push(`Connection ${city} <-> ${neighbor} is not bidirectional`)
      }
    }
  }

  // Check if all cities are connected (using BFS)
  if (Object.keys(neighbors).length > 0) {
    const visited = new Set<string>()
    const queue = [Object.keys(neighbors)[0]]
    visited.add(queue[0])

    while (queue.length > 0) {
      const current = queue.shift()!
      for (const neighbor of neighbors[current] || []) {
        if (!visited.has(neighbor)) {
          visited.add(neighbor)
          queue.push(neighbor)
        }
      }
    }

    if (visited.size !== Object.keys(neighbors).length) {
      errors.push(
        `Network is not fully connected. Connected: ${visited.size}, Total: ${Object.keys(neighbors).length}`,
      )
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}
