export enum Country {
  USA = 'usa',
  RUSSIA = 'russia',
  CHINA = 'china',
  UK = 'uk',
  FRANCE = 'france',
  GERMANY = 'germany',
  ISRAEL = 'israel',
  INDIA = 'india',
  JAPAN = 'japan',
  SOUTH_KOREA = 'south_korea',
  TURKEY = 'turkey',
  ITALY = 'italy',
  SWEDEN = 'sweden',
  SWITZERLAND = 'switzerland',
  UAE = 'uae',
  CANADA = 'canada',
  AUSTRALIA = 'australia',
  BRAZIL = 'brazil',
  SOUTH_AFRICA = 'south_africa',
  POLAND = 'poland',
  SPAIN = 'spain',
  NETHERLANDS = 'netherlands',
  BELGIUM = 'belgium',
  NORWAY = 'norway',
  SINGAPORE = 'singapore',
  SAUDI_ARABIA = 'saudi_arabia',
  EGYPT = 'egypt',
  PAKISTAN = 'pakistan',
  UKRAINE = 'ukraine',
  CZECH_REPUBLIC = 'czech_republic',
  MEXICO = 'mexico',
  ARGENTINA = 'argentina',
  INDONESIA = 'indonesia',
  THAILAND = 'thailand',
  VIETNAM = 'vietnam',
  PHILIPPINES = 'philippines',
  MALAYSIA = 'malaysia',
  GREECE = 'greece',
  ROMANIA = 'romania',
  FINLAND = 'finland',
  DENMARK = 'denmark',
  NEW_ZEALAND = 'new_zealand',
  CHILE = 'chile',
  COLOMBIA = 'colombia',
  IRAN = 'iran',
  IRAQ = 'iraq',
  SYRIA = 'syria',
  JORDAN = 'jordan',
  LEBANON = 'lebanon',
  NIGERIA = 'nigeria',
  KENYA = 'kenya',
  ETHIOPIA = 'ethiopia',
  MOROCCO = 'morocco',
  ALGERIA = 'algeria',
  PERU = 'peru',
  VENEZUELA = 'venezuela',
  ECUADOR = 'ecuador',
  AUSTRIA = 'austria',
  HUNGARY = 'hungary',
  BULGARIA = 'bulgaria',
  SERBIA = 'serbia',
  CROATIA = 'croatia',
  PORTUGAL = 'portugal',
  // Baltic states
  ESTONIA = 'estonia',
  LATVIA = 'latvia',
  LITHUANIA = 'lithuania',
  // Africa additions
  TANZANIA = 'tanzania',
  SUDAN = 'sudan',
  LIBYA = 'libya',
  TUNISIA = 'tunisia',
  GHANA = 'ghana',
  UGANDA = 'uganda',
  ZAMBIA = 'zambia',
  ZIMBABWE = 'zimbabwe',
  SENEGAL = 'senegal',
  ANGOLA = 'angola',
  // Oceania additions
  PAPUA_NEW_GUINEA = 'papua_new_guinea',
  FIJI = 'fiji',
  SOLOMON_ISLANDS = 'solomon_islands',
  VANUATU = 'vanuatu',
  SAMOA = 'samoa',
  TONGA = 'tonga',
  KIRIBATI = 'kiribati',
  MICRONESIA = 'micronesia',
  PALAU = 'palau',
  MARSHALL_ISLANDS = 'marshall_islands',
}

export const CountryNames: Record<Country, string> = {
  [Country.USA]: 'United States',
  [Country.RUSSIA]: 'Russia',
  [Country.CHINA]: 'China',
  [Country.UK]: 'United Kingdom',
  [Country.FRANCE]: 'France',
  [Country.GERMANY]: 'Germany',
  [Country.ISRAEL]: 'Israel',
  [Country.INDIA]: 'India',
  [Country.JAPAN]: 'Japan',
  [Country.SOUTH_KOREA]: 'South Korea',
  [Country.TURKEY]: 'Turkey',
  [Country.ITALY]: 'Italy',
  [Country.SWEDEN]: 'Sweden',
  [Country.SWITZERLAND]: 'Switzerland',
  [Country.UAE]: 'United Arab Emirates',
  [Country.CANADA]: 'Canada',
  [Country.AUSTRALIA]: 'Australia',
  [Country.BRAZIL]: 'Brazil',
  [Country.SOUTH_AFRICA]: 'South Africa',
  [Country.POLAND]: 'Poland',
  [Country.SPAIN]: 'Spain',
  [Country.NETHERLANDS]: 'Netherlands',
  [Country.BELGIUM]: 'Belgium',
  [Country.NORWAY]: 'Norway',
  [Country.SINGAPORE]: 'Singapore',
  [Country.SAUDI_ARABIA]: 'Saudi Arabia',
  [Country.EGYPT]: 'Egypt',
  [Country.PAKISTAN]: 'Pakistan',
  [Country.UKRAINE]: 'Ukraine',
  [Country.CZECH_REPUBLIC]: 'Czech Republic',
  [Country.MEXICO]: 'Mexico',
  [Country.ARGENTINA]: 'Argentina',
  [Country.INDONESIA]: 'Indonesia',
  [Country.THAILAND]: 'Thailand',
  [Country.VIETNAM]: 'Vietnam',
  [Country.PHILIPPINES]: 'Philippines',
  [Country.MALAYSIA]: 'Malaysia',
  [Country.GREECE]: 'Greece',
  [Country.ROMANIA]: 'Romania',
  [Country.FINLAND]: 'Finland',
  [Country.DENMARK]: 'Denmark',
  [Country.NEW_ZEALAND]: 'New Zealand',
  [Country.CHILE]: 'Chile',
  [Country.COLOMBIA]: 'Colombia',
  [Country.IRAN]: 'Iran',
  [Country.IRAQ]: 'Iraq',
  [Country.SYRIA]: 'Syria',
  [Country.JORDAN]: 'Jordan',
  [Country.LEBANON]: 'Lebanon',
  [Country.NIGERIA]: 'Nigeria',
  [Country.KENYA]: 'Kenya',
  [Country.ETHIOPIA]: 'Ethiopia',
  [Country.MOROCCO]: 'Morocco',
  [Country.ALGERIA]: 'Algeria',
  [Country.PERU]: 'Peru',
  [Country.VENEZUELA]: 'Venezuela',
  [Country.ECUADOR]: 'Ecuador',
  [Country.AUSTRIA]: 'Austria',
  [Country.HUNGARY]: 'Hungary',
  [Country.BULGARIA]: 'Bulgaria',
  [Country.SERBIA]: 'Serbia',
  [Country.CROATIA]: 'Croatia',
  [Country.PORTUGAL]: 'Portugal',
  // Baltic states
  [Country.ESTONIA]: 'Estonia',
  [Country.LATVIA]: 'Latvia',
  [Country.LITHUANIA]: 'Lithuania',
  // Africa additions
  [Country.TANZANIA]: 'Tanzania',
  [Country.SUDAN]: 'Sudan',
  [Country.LIBYA]: 'Libya',
  [Country.TUNISIA]: 'Tunisia',
  [Country.GHANA]: 'Ghana',
  [Country.UGANDA]: 'Uganda',
  [Country.ZAMBIA]: 'Zambia',
  [Country.ZIMBABWE]: 'Zimbabwe',
  [Country.SENEGAL]: 'Senegal',
  [Country.ANGOLA]: 'Angola',
  // Oceania additions
  [Country.PAPUA_NEW_GUINEA]: 'Papua New Guinea',
  [Country.FIJI]: 'Fiji',
  [Country.SOLOMON_ISLANDS]: 'Solomon Islands',
  [Country.VANUATU]: 'Vanuatu',
  [Country.SAMOA]: 'Samoa',
  [Country.TONGA]: 'Tonga',
  [Country.KIRIBATI]: 'Kiribati',
  [Country.MICRONESIA]: 'Micronesia',
  [Country.PALAU]: 'Palau',
  [Country.MARSHALL_ISLANDS]: 'Marshall Islands',
}
