export enum Country {
  USA = 'usa',
  RUSSIA = 'russia',
  CHINA = 'china',
  UK = 'uk',
  FRANCE = 'france',
  GERMANY = 'germany',
  ISRAEL = 'israel',
  INDIA = 'india',
  JAPAN = 'japan',
  SOUTH_KOREA = 'south_korea',
  TURKEY = 'turkey',
  ITALY = 'italy',
  SWEDEN = 'sweden',
  SWITZERLAND = 'switzerland',
  UAE = 'uae',
  CANADA = 'canada',
  AUSTRALIA = 'australia',
  BRAZIL = 'brazil',
  SOUTH_AFRICA = 'south_africa',
  POLAND = 'poland',
  SPAIN = 'spain',
  NETHERLANDS = 'netherlands',
  BELGIUM = 'belgium',
  NORWAY = 'norway',
  SINGAPORE = 'singapore',
  SAUDI_ARABIA = 'saudi_arabia',
  EGYPT = 'egypt',
  PAKISTAN = 'pakistan',
  UKRAINE = 'ukraine',
  CZECH_REPUBLIC = 'czech_republic',
  MEXICO = 'mexico',
  ARGENTINA = 'argentina',
  INDONESIA = 'indonesia',
  THAILAND = 'thailand',
  VIETNAM = 'vietnam',
  PHILIPPINES = 'philippines',
  MALAYSIA = 'malaysia',
  GREECE = 'greece',
  ROMANIA = 'romania',
  FINLAND = 'finland',
  DENMARK = 'denmark',
  NEW_ZEALAND = 'new_zealand',
  CHILE = 'chile',
  COLOMBIA = 'colombia',
  IRAN = 'iran',
  IRAQ = 'iraq',
  SYRIA = 'syria',
  JORDAN = 'jordan',
  LEBANON = 'lebanon',
  NIGERIA = 'nigeria',
  KENYA = 'kenya',
  ETHIOPIA = 'ethiopia',
  MOROCCO = 'morocco',
  ALGERIA = 'algeria',
  PERU = 'peru',
  VENEZUELA = 'venezuela',
  ECUADOR = 'ecuador',
  AUSTRIA = 'austria',
  HUNGARY = 'hungary',
  BULGARIA = 'bulgaria',
  SERBIA = 'serbia',
  CROATIA = 'croatia',
  PORTUGAL = 'portugal',
}

export const CountryNames: Record<Country, string> = {
  [Country.USA]: 'United States',
  [Country.RUSSIA]: 'Russia',
  [Country.CHINA]: 'China',
  [Country.UK]: 'United Kingdom',
  [Country.FRANCE]: 'France',
  [Country.GERMANY]: 'Germany',
  [Country.ISRAEL]: 'Israel',
  [Country.INDIA]: 'India',
  [Country.JAPAN]: 'Japan',
  [Country.SOUTH_KOREA]: 'South Korea',
  [Country.TURKEY]: 'Turkey',
  [Country.ITALY]: 'Italy',
  [Country.SWEDEN]: 'Sweden',
  [Country.SWITZERLAND]: 'Switzerland',
  [Country.UAE]: 'United Arab Emirates',
  [Country.CANADA]: 'Canada',
  [Country.AUSTRALIA]: 'Australia',
  [Country.BRAZIL]: 'Brazil',
  [Country.SOUTH_AFRICA]: 'South Africa',
  [Country.POLAND]: 'Poland',
  [Country.SPAIN]: 'Spain',
  [Country.NETHERLANDS]: 'Netherlands',
  [Country.BELGIUM]: 'Belgium',
  [Country.NORWAY]: 'Norway',
  [Country.SINGAPORE]: 'Singapore',
  [Country.SAUDI_ARABIA]: 'Saudi Arabia',
  [Country.EGYPT]: 'Egypt',
  [Country.PAKISTAN]: 'Pakistan',
  [Country.UKRAINE]: 'Ukraine',
  [Country.CZECH_REPUBLIC]: 'Czech Republic',
  [Country.MEXICO]: 'Mexico',
  [Country.ARGENTINA]: 'Argentina',
  [Country.INDONESIA]: 'Indonesia',
  [Country.THAILAND]: 'Thailand',
  [Country.VIETNAM]: 'Vietnam',
  [Country.PHILIPPINES]: 'Philippines',
  [Country.MALAYSIA]: 'Malaysia',
  [Country.GREECE]: 'Greece',
  [Country.ROMANIA]: 'Romania',
  [Country.FINLAND]: 'Finland',
  [Country.DENMARK]: 'Denmark',
  [Country.NEW_ZEALAND]: 'New Zealand',
  [Country.CHILE]: 'Chile',
  [Country.COLOMBIA]: 'Colombia',
  [Country.IRAN]: 'Iran',
  [Country.IRAQ]: 'Iraq',
  [Country.SYRIA]: 'Syria',
  [Country.JORDAN]: 'Jordan',
  [Country.LEBANON]: 'Lebanon',
  [Country.NIGERIA]: 'Nigeria',
  [Country.KENYA]: 'Kenya',
  [Country.ETHIOPIA]: 'Ethiopia',
  [Country.MOROCCO]: 'Morocco',
  [Country.ALGERIA]: 'Algeria',
  [Country.PERU]: 'Peru',
  [Country.VENEZUELA]: 'Venezuela',
  [Country.ECUADOR]: 'Ecuador',
  [Country.AUSTRIA]: 'Austria',
  [Country.HUNGARY]: 'Hungary',
  [Country.BULGARIA]: 'Bulgaria',
  [Country.SERBIA]: 'Serbia',
  [Country.CROATIA]: 'Croatia',
  [Country.PORTUGAL]: 'Portugal',
}
