export enum Country {
  USA = 'usa',
  RUSSIA = 'russia',
  CHINA = 'china',
  UK = 'uk',
  FRANCE = 'france',
  GERMANY = 'germany',
  ISRAEL = 'israel',
  INDIA = 'india',
  JAPAN = 'japan',
  SOUTH_KOREA = 'south_korea',
  TURKEY = 'turkey',
  ITALY = 'italy',
  SWEDEN = 'sweden',
  SWITZERLAND = 'switzerland',
  UAE = 'uae',
  CANADA = 'canada',
  AUSTRALIA = 'australia',
  BRAZIL = 'brazil',
  SOUTH_AFRICA = 'south_africa',
  POLAND = 'poland',
  SPAIN = 'spain',
  NETHERLANDS = 'netherlands',
  BELGIUM = 'belgium',
  NORWAY = 'norway',
  SINGAPORE = 'singapore',
  SAUDI_ARABIA = 'saudi_arabia',
  EGYPT = 'egypt',
  PAKISTAN = 'pakistan',
  UKRAINE = 'ukraine',
  CZECH_REPUBLIC = 'czech_republic',
}

export const CountryNames: Record<Country, string> = {
  [Country.USA]: 'United States',
  [Country.RUSSIA]: 'Russia',
  [Country.CHINA]: 'China',
  [Country.UK]: 'United Kingdom',
  [Country.FRANCE]: 'France',
  [Country.GERMANY]: 'Germany',
  [Country.ISRAEL]: 'Israel',
  [Country.INDIA]: 'India',
  [Country.JAPAN]: 'Japan',
  [Country.SOUTH_KOREA]: 'South Korea',
  [Country.TURKEY]: 'Turkey',
  [Country.ITALY]: 'Italy',
  [Country.SWEDEN]: 'Sweden',
  [Country.SWITZERLAND]: 'Switzerland',
  [Country.UAE]: 'United Arab Emirates',
  [Country.CANADA]: 'Canada',
  [Country.AUSTRALIA]: 'Australia',
  [Country.BRAZIL]: 'Brazil',
  [Country.SOUTH_AFRICA]: 'South Africa',
  [Country.POLAND]: 'Poland',
  [Country.SPAIN]: 'Spain',
  [Country.NETHERLANDS]: 'Netherlands',
  [Country.BELGIUM]: 'Belgium',
  [Country.NORWAY]: 'Norway',
  [Country.SINGAPORE]: 'Singapore',
  [Country.SAUDI_ARABIA]: 'Saudi Arabia',
  [Country.EGYPT]: 'Egypt',
  [Country.PAKISTAN]: 'Pakistan',
  [Country.UKRAINE]: 'Ukraine',
  [Country.CZECH_REPUBLIC]: 'Czech Republic',
}
