import { Country } from './Countries.ts'

export enum RegimeType {
  DEMOCRACY = 'democracy',
  TOTALITARIAN = 'totalitarian',
  AUTHORITARIAN = 'authoritarian',
  MONARCHY = 'monarchy',
  THEOCRACY = 'theocracy',
  MILITARY_JUNTA = 'military_junta',
  OLIGARCHY = 'oligarchy',
}

export enum PoliticalStance {
  ISOLATIONIST = 'isolationist',
  INTERVENTIONIST = 'interventionist',
  EXPANSIONIST = 'expansionist',
  NEUTRAL = 'neutral',
  DEFENSIVE = 'defensive',
  COOPERATIVE = 'cooperative',
}

export interface BranchCapabilities {
  army: number // 1-5
  navy: number // 1-5
  airforce: number // 1-5
}

export interface CountryAttributeData {
  budget: number // Military budget (1-5)
  standards: number // Sensitivity to ordnance quality (1-5)
  corruption: number // Corruption level (1-5)
  visibility: number // How observed operations are (1-5)
  regime: RegimeType
  industrialProduction: BranchCapabilities // Per branch production capability (1-5)
  industrialTech: BranchCapabilities // Per branch tech level (1-5)
  politicalStance: PoliticalStance
}

export const CountryAttributes: Record<Country, CountryAttributeData> = {
  // Major Powers
  [Country.USA]: {
    budget: 5,
    standards: 5,
    corruption: 2,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 5, navy: 5, airforce: 5 },
    industrialTech: { army: 5, navy: 5, airforce: 5 },
    politicalStance: PoliticalStance.INTERVENTIONIST,
  },
  [Country.CHINA]: {
    budget: 5,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 5, navy: 4, airforce: 4 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.EXPANSIONIST,
  },
  [Country.RUSSIA]: {
    budget: 4,
    standards: 3,
    corruption: 4,
    visibility: 4,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 4, navy: 3, airforce: 4 },
    industrialTech: { army: 4, navy: 3, airforce: 4 },
    politicalStance: PoliticalStance.EXPANSIONIST,
  },
  [Country.INDIA]: {
    budget: 3,
    standards: 3,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 4, navy: 3, airforce: 3 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.UK]: {
    budget: 4,
    standards: 5,
    corruption: 2,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 4, airforce: 4 },
    industrialTech: { army: 4, navy: 5, airforce: 5 },
    politicalStance: PoliticalStance.INTERVENTIONIST,
  },
  [Country.FRANCE]: {
    budget: 3,
    standards: 4,
    corruption: 2,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.INTERVENTIONIST,
  },
  [Country.GERMANY]: {
    budget: 3,
    standards: 5,
    corruption: 2,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 4, navy: 3, airforce: 3 },
    industrialTech: { army: 5, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.JAPAN]: {
    budget: 3,
    standards: 5,
    corruption: 2,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 4, airforce: 3 },
    industrialTech: { army: 5, navy: 5, airforce: 5 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.SOUTH_KOREA]: {
    budget: 3,
    standards: 4,
    corruption: 2,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.ISRAEL]: {
    budget: 3,
    standards: 5,
    corruption: 2,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 2, airforce: 3 },
    industrialTech: { army: 5, navy: 4, airforce: 5 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.SAUDI_ARABIA]: {
    budget: 4,
    standards: 4,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.MONARCHY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.TURKEY]: {
    budget: 3,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.INTERVENTIONIST,
  },
  [Country.ITALY]: {
    budget: 3,
    standards: 4,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.SPAIN]: {
    budget: 2,
    standards: 3,
    corruption: 2,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.CANADA]: {
    budget: 2,
    standards: 4,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.AUSTRALIA]: {
    budget: 2,
    standards: 4,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.BRAZIL]: {
    budget: 2,
    standards: 3,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.MEXICO]: {
    budget: 2,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.ARGENTINA]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.SOUTH_AFRICA]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.POLAND]: {
    budget: 2,
    standards: 3,
    corruption: 2,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.UKRAINE]: {
    budget: 2,
    standards: 3,
    corruption: 4,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 2, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.NETHERLANDS]: {
    budget: 2,
    standards: 4,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 3, airforce: 2 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.BELGIUM]: {
    budget: 2,
    standards: 4,
    corruption: 2,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 4, navy: 3, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.SWEDEN]: {
    budget: 2,
    standards: 5,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 3, airforce: 3 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.SWITZERLAND]: {
    budget: 2,
    standards: 5,
    corruption: 1,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 4, navy: 2, airforce: 4 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.UAE]: {
    budget: 3,
    standards: 4,
    corruption: 2,
    visibility: 3,
    regime: RegimeType.MONARCHY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.EGYPT]: {
    budget: 2,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 2, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.PAKISTAN]: {
    budget: 2,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 3, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 2, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.SINGAPORE]: {
    budget: 2,
    standards: 5,
    corruption: 1,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 2, airforce: 2 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.INDONESIA]: {
    budget: 2,
    standards: 2,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.THAILAND]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.MILITARY_JUNTA,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.VIETNAM]: {
    budget: 2,
    standards: 2,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.PHILIPPINES]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.MALAYSIA]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.NEW_ZEALAND]: {
    budget: 1,
    standards: 4,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 2, airforce: 1 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.NIGERIA]: {
    budget: 2,
    standards: 2,
    corruption: 5,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.KENYA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.ETHIOPIA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 2 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.MOROCCO]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.MONARCHY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.ALGERIA]: {
    budget: 2,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  // Additional Middle East countries
  [Country.IRAN]: {
    budget: 3,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.THEOCRACY,
    industrialProduction: { army: 3, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 2, airforce: 3 },
    politicalStance: PoliticalStance.EXPANSIONIST,
  },
  [Country.IRAQ]: {
    budget: 2,
    standards: 2,
    corruption: 5,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 2 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.SYRIA]: {
    budget: 1,
    standards: 1,
    corruption: 5,
    visibility: 2,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 2 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.JORDAN]: {
    budget: 1,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.MONARCHY,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 2, navy: 1, airforce: 2 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.LEBANON]: {
    budget: 1,
    standards: 2,
    corruption: 5,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  // European countries
  [Country.NORWAY]: {
    budget: 2,
    standards: 5,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 3, airforce: 2 },
    industrialTech: { army: 4, navy: 4, airforce: 4 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.DENMARK]: {
    budget: 2,
    standards: 4,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 4, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.FINLAND]: {
    budget: 2,
    standards: 4,
    corruption: 1,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 4, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.AUSTRIA]: {
    budget: 1,
    standards: 4,
    corruption: 2,
    visibility: 5,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 3, navy: 1, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.CZECH_REPUBLIC]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 3, navy: 1, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.HUNGARY]: {
    budget: 1,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 3, navy: 1, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.ROMANIA]: {
    budget: 2,
    standards: 3,
    corruption: 4,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 2, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.BULGARIA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.GREECE]: {
    budget: 2,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 3, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.SERBIA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.CROATIA]: {
    budget: 1,
    standards: 3,
    corruption: 3,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.PORTUGAL]: {
    budget: 2,
    standards: 3,
    corruption: 2,
    visibility: 4,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 3, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  // South American countries
  [Country.CHILE]: {
    budget: 2,
    standards: 3,
    corruption: 2,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 3, navy: 3, airforce: 3 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.COLOMBIA]: {
    budget: 2,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 2 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.PERU]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 2, navy: 2, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.VENEZUELA]: {
    budget: 1,
    standards: 1,
    corruption: 5,
    visibility: 2,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.ISOLATIONIST,
  },
  [Country.ECUADOR]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 2,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  // New Africa countries
  [Country.TANZANIA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.SUDAN]: {
    budget: 1,
    standards: 1,
    corruption: 5,
    visibility: 2,
    regime: RegimeType.MILITARY_JUNTA,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.ISOLATIONIST,
  },
  [Country.LIBYA]: {
    budget: 2,
    standards: 2,
    corruption: 5,
    visibility: 2,
    regime: RegimeType.MILITARY_JUNTA,
    industrialProduction: { army: 2, navy: 1, airforce: 2 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.EXPANSIONIST,
  },
  [Country.TUNISIA]: {
    budget: 1,
    standards: 2,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.GHANA]: {
    budget: 1,
    standards: 2,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.UGANDA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 2,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.DEFENSIVE,
  },
  [Country.ZAMBIA]: {
    budget: 1,
    standards: 2,
    corruption: 4,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.ZIMBABWE]: {
    budget: 1,
    standards: 1,
    corruption: 5,
    visibility: 2,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.ISOLATIONIST,
  },
  [Country.SENEGAL]: {
    budget: 1,
    standards: 2,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 1 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.ANGOLA]: {
    budget: 2,
    standards: 2,
    corruption: 5,
    visibility: 2,
    regime: RegimeType.AUTHORITARIAN,
    industrialProduction: { army: 2, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 2 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  // New Oceania countries
  [Country.PAPUA_NEW_GUINEA]: {
    budget: 1,
    standards: 1,
    corruption: 4,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.FIJI]: {
    budget: 1,
    standards: 2,
    corruption: 3,
    visibility: 3,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 2, navy: 2, airforce: 1 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.SOLOMON_ISLANDS]: {
    budget: 1,
    standards: 1,
    corruption: 4,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.VANUATU]: {
    budget: 1,
    standards: 1,
    corruption: 3,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.SAMOA]: {
    budget: 1,
    standards: 2,
    corruption: 2,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.TONGA]: {
    budget: 1,
    standards: 2,
    corruption: 2,
    visibility: 1,
    regime: RegimeType.MONARCHY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.KIRIBATI]: {
    budget: 1,
    standards: 1,
    corruption: 3,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.NEUTRAL,
  },
  [Country.MICRONESIA]: {
    budget: 1,
    standards: 1,
    corruption: 3,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.PALAU]: {
    budget: 1,
    standards: 2,
    corruption: 2,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
  [Country.MARSHALL_ISLANDS]: {
    budget: 1,
    standards: 1,
    corruption: 3,
    visibility: 1,
    regime: RegimeType.DEMOCRACY,
    industrialProduction: { army: 1, navy: 1, airforce: 1 },
    industrialTech: { army: 1, navy: 1, airforce: 1 },
    politicalStance: PoliticalStance.COOPERATIVE,
  },
}